### ISSUE TITLE
无法启动了……

### ISSUE THREAD

**Issue by ViKingQ** [tonyleelyy/OpenCore-Hackintosh-Dell-G3-3579#10]
我的是双系统macos10.14.2和win10，下载的0.5.7版本的OC，解压后把EFI下的OC整个目录替换成你提供的OC目录，然后将整个EFI替换掉之前的clover版的EFI分区，重启后俩系统都进不去了

**Comment by tonyleelyy** [comment]
请提供更加详细的报错信息或者图片说明，不然我帮不了你。

另外我的OC不支持引导Windows，必须直接开机F12选择自带的UEFI启动，如果你把EFI里的Microsoft目录删了的话...只能进pe恢复了

有些看不懂你下载0.5.7版OC的操作，我这个efi就是0.5.7的官方版了，直接复制我的到EFI目录就行了。

**Comment by ViKingQ** [comment]
> 请提供更加详细的报错信息或者图片说明，不然我帮不了你。
> 
> 另外我的OC不支持引导Windows，必须直接开机F12选择自带的UEFI启动，如果你把EFI里的Microsoft目录删了的话...只能进pe恢复了
> 
> 有些看不懂你下载0.5.7版OC的操作，我这个efi就是0.5.7的官方版了，直接复制我的到EFI目录就行了。

BIOS配置需要改哪些东西，我看到网上其他clover转oc教程里说要改bios配置，但是教程里列的配置项我在bios里都没找到。您能给提供一下需要改的bios配置项吗？不胜感激……

**Comment by tonyleelyy** [comment]
> 
> BIOS配置需要改哪些东西，我看到网上其他clover转oc教程里说要改bios配置，但是教程里列的配置项我在bios里都没找到。您能给提供一下需要改的bios配置项吗？不胜感激……

稍等，这得找一下，我尽快搞定

**Comment by tonyleelyy** [comment]
> BIOS配置需要改哪些东西，我看到网上其他clover转oc教程里说要改bios配置，但是教程里列的配置项我在bios里都没找到。您能给提供一下需要改的bios配置项吗？不胜感激……


System Configuration
SATA Operation - AHCI

Secure Boot
Secure Boot Enable - 取消勾选

Intel Software Guard Extensions
Intel SGX Enable - Disabled

POST Behavior 
Fastboot - Thorough

Virtualization Support
VT for Direct I/O - 取消勾选

这是我改的东西，bios已升级到最新版本

**Comment by ViKingQ** [comment]
谢谢！晚上回去我试一下

**Comment by ViKingQ** [comment]
我把EFI全部恢复了，用Clover可以引导了，我已经按照你的BIOS配置操作好了，下一步该如何操作？
直接把你的OC目录复制到我的EFI目录下，然后BIOS中添加EFI/OC/OpenCore.efi作为启动项就行吗？

**Comment by tonyleelyy** [comment]
> 我把EFI全部恢复了，用Clover可以引导了，我已经按照你的BIOS配置操作好了，下一步该如何操作？
> 
> 直接把你的OC目录复制到我的EFI目录下，然后BIOS中添加EFI/OC/OpenCore.efi作为启动项就行吗？

没有错！第一次使用建议你直接使用我的EFI_Install.zip。

不要用我的OC来引导Windows，你之前怎么启动Windows的就继续怎么启动就好。

启动过程中如果有什么报错之类，记得拍照或者录像记录一下哦！

祝你好运！

**Comment by ViKingQ** [comment]
可以了。

后来但是我手贱，把跟ESP分区并列的俩分区（好像是恢复和MBR）给删了。又启动不了了!😭[image](https://user-images.githubusercontent.com/19511674/80667246-34fcc480-8ad1-11ea-8d6d-5af9a983c734.jpeg)

**Comment by ViKingQ** [comment]
本来可以了，

后来我手贱，看跟ESP分区并列的俩分区（“恢复”和“MBR"）里没啥东西，就把这俩分区给删除了，现在又启动不了了，大佬，这还能恢复吗？
![IMG_0433 HEIC JPG](https://user-images.githubusercontent.com/19511674/80667468-cec47180-8ad1-11ea-9a71-f96da129ca13.JPG)

**Comment by tonyleelyy** [comment]
这两个分区不影响启动的呀，我之前重装电脑也删除了这两个分区。

请问是macOS启动不了还是Windows启动不了？

**Comment by ViKingQ** [comment]
可以了，我删那俩分区的时候，不知道为啥EFI下的OC目录也没了。
再问一下，我目前的macos是10.14.2 能在系统里直接更新到10.15.4吗？

**Comment by tonyleelyy** [comment]
> 可以了，我删那俩分区的时候，不知道为啥EFI下的OC目录也没了。
> 
> 再问一下，我目前的macos是10.14.2 能在系统里直接更新到10.15.4吗？

可以直接更新的！毫无压力～ 建议你用showpicker 为打开状态的 config.plist 进行更新，手动选择启动项。

**Comment by ViKingQ** [comment]
嗯好。晚上抽时间更新一下，多谢

**Comment by ViKingQ** [comment]
还有个问题，OC引导下，如何生成那个三码，在mac上使用FaceTime  并且登录appleid 不被封

**Comment by tonyleelyy** [comment]
> 还有个问题，OC引导下，如何生成那个三码，在mac上使用FaceTime 并且登录appleid 不被封

跟Clover的方法类似，

你可以使用[OpenCore Configurator](https://mackie100projects.altervista.org/opencore-configurator/)生成三码信息，然后使用[ProperTree](https://github.com/corpnewt/ProperTree)打开config.plist填入PlatformInfo中。

注意我们戴尔笔记本需要DataHub、Generic、PlatformNVRAM、SMBIOS四项都填完整，不能像教程说的那样自动生成。
