### ISSUE TITLE
Help with instalattion

### ISSUE THREAD

**Issue by lucasbordini** [tonyleelyy/OpenCore-Hackintosh-Dell-G3-3579#11]
Hey man, can you help me with installation?

I have the MacOs Catalina img but dunno how to put this files there

**Comment by tonyleelyy** [comment]
> Hey man, can you help me with installation?
> 
> 
> 
> I have the MacOs Catalina img but dunno how to put this files there

I’m sorry that I can’t. I’m just a student and I don't have much time helping you cuz the installation takes a long time.

Please check the installation guides online. I would like to recommend some of them to you: 

- https://dortania.github.io/OpenCore-Desktop-Guide/installer-guide/#making-the-installer
- https://www.tonymacx86.com/threads/unibeast-install-macos-catalina-on-any-supported-intel-based-pc.285366/
- If you can understand Chinese, check the installation guide written by myself: https://tonyleelyy.top/42403/

Hope these can help you! Good luck!

**Comment by tonyleelyy** [comment]
> Hey man, can you help me with installation?
> 
> 
> 
> I have the MacOs Catalina img but dunno how to put this files there

I’m sorry that I can’t. I’m just a student and I don't have much time helping you cuz the installation takes a long time.

Please check the installation guides online. I would like to recommend some of them to you: 

- https://dortania.github.io/OpenCore-Desktop-Guide/installer-guide/#making-the-installer
- https://www.tonymacx86.com/threads/unibeast-install-macos-catalina-on-any-supported-intel-based-pc.285366/
- If you can understand Chinese, check the installation guide written by myself: https://tonyleelyy.top/42403/

Hope these can help you! Good luck!
