### ISSUE TITLE
请问boot文件夹有什么讲究嘛

### ISSUE THREAD

**Issue by baobaodeya** [tonyleelyy/OpenCore-Hackintosh-Dell-G3-3579#12]
（尽管我的问题很wake）感觉我看了那么多教程都是直接把efi文件夹复制进U盘efi分区。然后看了上面的issues你讲每个电脑的boot都不一样。那要怎么得到这个boot文件夹呢？

**Comment by tonyleelyy** [comment]
我的这个观点是错的，BOOT是可以替换的。

但我们这电脑不需要改BOOT文件夹，直接在BIOS里加入OpenCore.efi作为启动项就能启动。

不过我最近听说用BOOT来引导是更稳的，你可以下载[OpenCore的release](https://github.com/acidanthera/OpenCorePkg/releases/tag/0.5.8)，里面的EFI文件夹下就有BOOT文件夹，备份原文件并替换即可~

我之后会在这个项目中添加上这个BOOT文件夹。

**Comment by baobaodeya** [comment]
我之前按照你的bios清单设置了下bios
完了这边直接用你提供的oc文件放efi下的话U盘引导不了，进戴尔白色的自检了。
bios里也加不了opencore.efi，提示boot name not find

是有什么被我忽略了吗？

**Comment by tonyleelyy** [comment]
> 我之前按照你的bios清单设置了下bios
> 完了这边直接用你提供的oc文件放efi下的话U盘引导不了，进戴尔白色的自检了。
> bios里也加不了opencore.efi，提示boot name not find
> 
> 是有什么被我忽略了吗？

我好像没遇到过这种问题，检查一下以下的几种情况吧：
1. 更新一下BIOS。
2. 添加引导的时候要给它填个名字的，填了没？
3. 安装的时候使用我的EFI_Install.zip。
4. 在Windows下使用BOOTICE添加引导试试。

**Comment by baobaodeya** [comment]
Ok了😂我最开始用的EFI.ZIP这个 然后我寻思不对劲换用了install_efi.zip 用easyuefi做了启动项。 非常感谢😃------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;tonyleelyy&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年5月23日(星期六) 下午4:25
收件人:&nbsp;&quot;tonyleelyy/OpenCore-Hackintosh-Dell-G3-3579&quot;<OpenCore-Hackintosh-Dell-G3-3579@noreply.github.com&gt;;
抄送:&nbsp;&quot;baobaodeya&quot;<baobaodeya@vip.qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [tonyleelyy/OpenCore-Hackintosh-Dell-G3-3579] 请问boot文件夹有什么讲究嘛 (#12)

**Comment by tonyleelyy** [comment]
嘻嘻，祝你玩得开心！
