### ISSUE TITLE
启动时遇到错误

### ISSUE THREAD

**Issue by aiyunyuner** [tonyleelyy/OpenCore-Hackintosh-Dell-G3-3579#13]
![337B35EE-D04B-4214-8D85-9D6EB2293E42](https://user-images.githubusercontent.com/63837650/82746086-8e010500-9dbe-11ea-90de-39aa6d4a35b8.png)
启动时遇到错误，该怎么解决

**Comment by tonyleelyy** [comment]
没见过这样的错误，请自行检查：
1. BIOS设置是否正确，是否已更新到最新的BIOS
2. 是否使用EFI_Install.zip安装，并手动选择启动项
3. U盘刻录的镜像是否损坏了

**Comment by aiyunyuner** [comment]
好的

**Comment by aiyunyuner** [comment]
![618C8F10-C844-4F2D-93C6-0E1F4D1B6DA0](https://user-images.githubusercontent.com/63837650/82748807-5b173b00-9dd7-11ea-8371-2222da4c289e.jpeg)
bulid 出现错误

**Comment by tonyleelyy** [comment]
我的这个教程已经过时了，还没有空更新

看[这个](http://bbs.pcbeta.com/forum.php?mod=viewthread&tid=1856461&highlight=%B1%E0%D2%EB)来重试编译，或者直接用另一个驱动，[链接](http://bbs.pcbeta.com/viewthread-1856465-1-2.html)。

**Comment by aiyunyuner** [comment]
![ADCD1A42-914D-4B9D-814C-3672A6E085E4](https://user-images.githubusercontent.com/63837650/82753530-e94fe900-9df8-11ea-9f78-905413a91b70.png)
已成功。

**Comment by tonyleelyy** [comment]
恭喜恭喜！
