### ISSUE TITLE
不能正常关机

### ISSUE THREAD

**Issue by aiyunyuner** [tonyleelyy/OpenCore-Hackintosh-Dell-G3-3579#14]
在mac中，点了关机。屏幕是黑了，但是键盘灯没有熄灭，同时风扇仍然在工作。

**Comment by aiyunyuner** [comment]
我关机每次关机只能长按开机键关机

**Comment by tonyleelyy** [comment]
> 在mac中，点了关机。屏幕是黑了，但是键盘灯没有熄灭，同时风扇仍然在工作。

请问键盘灯是指自带键盘的灯？还是你外接USB的灯？

**Comment by aiyunyuner** [comment]
自带键盘的灯

**Comment by tonyleelyy** [comment]
> 自带键盘的灯

已找到问题所在，正在解决，稍安。

**Comment by aiyunyuner** [comment]
好的，辛苦了。

**Comment by aiyunyuner** [comment]
将电脑屏幕合上过了一段时间后，再将屏幕打开，不能唤醒系统，只有键盘灯是亮的，屏幕仍然黑的

**Comment by tonyleelyy** [comment]
> 将电脑屏幕合上过了一段时间后，再将屏幕打开，不能唤醒系统，只有键盘灯是亮的，屏幕仍然黑的

这问题非常棘手，我正在和我的朋友全力解决这个问题（他也出现了这个问题，但我没有），可能还需要一定时间。

**Comment by aiyunyuner** [comment]
感谢你们的付出。

**Comment by tonyleelyy** [comment]
> 将电脑屏幕合上过了一段时间后，再将屏幕打开，不能唤醒系统，只有键盘灯是亮的，屏幕仍然黑的

请问你在Windows下会存在关机不断电的问题吗？

**Comment by aiyunyuner** [comment]
有的

**Comment by aiyunyuner** [comment]
我也是后来才发现的

**Comment by aiyunyuner** [comment]
这个问题能解决吗？

**Comment by tonyleelyy** [comment]
> 这个问题能解决吗？

是这样的，我和我的那位朋友已经研究了3天，下面给你说说暂时的解决方法。

他的电脑是Dell G3 3579，配置和我的完全一样，原本没有背光键盘。之前他键盘不慎进水，就换了一个背光键盘，之后安装黑苹果就出现了关机不断电的问题，而且是Windows和macOS都会出现，跟你的情况一样。

我们尝试了一堆方法，各种排查也还是无法解决。结果看到远景上面一个很骚的方法：安装Ubuntu，Windows和黑苹果的关机问题就消失了。

所以如果你急着用的话，可以安装Ubuntu，这个问题就神奇地解决了。我也真是不知道这是什么问题导致的。

**Comment by aiyunyuner** [comment]
安装实体的Ubuntu吗？，还是虚拟机？

**Comment by aiyunyuner** [comment]
辛苦了，这个方法果然很骚。。。

**Comment by tonyleelyy** [comment]
> 安装实体的Ubuntu吗？，还是虚拟机？

实体的，你使用一个U盘安装即可！

**Comment by tonyleelyy** [comment]
我稍后会发布一个修正更新，你可以选择先尝试一下那个版本的EFI，虽然大概率还是不行的...

**Comment by aiyunyuner** [comment]
好的，我现在就去试试

**Comment by aiyunyuner** [comment]
好的，我先试试更新版，如果不行我再安装

**Comment by aiyunyuner** [comment]
请问你只是装了mac就没有这样的情况吗？

**Comment by tonyleelyy** [comment]
> 请问你只是装了mac就没有这样的情况吗？

并不是哦，我同样安装了Windows。

而我的电脑和我那位朋友的电脑，唯二的区别就是，他改装了背光键盘而我没有，他的mac装在了机械硬盘中而我装在了固态硬盘中。

不知道为何就造成了这样的问题。

**Comment by aiyunyuner** [comment]
巧了，我也是装在机械中的难道是不能装在机械里的缘故吗？

**Comment by tonyleelyy** [comment]
> 巧了，我也是装在机械中的难道是不能装在机械里的缘故吗？

应该不会。而且这也不能解释安装了Ubuntu问题就消失了的现象...

**Comment by tonyleelyy** [comment]
> 好的，我先试试更新版，如果不行我再安装

新版本已经发布了，试试吧！

**Comment by aiyunyuner** [comment]
还是不行的，看来我要去安装Ubuntu一下试试

**Comment by aiyunyuner** [comment]
我已安装Ubuntu，果然有效。请问当我删除mac后别oc修改过的bios还能复原吗？例如：fn与f1到f12按键恢复原来的样子

**Comment by tonyleelyy** [comment]
> 我已安装Ubuntu，果然有效。请问当我删除mac后别oc修改过的bios还能复原吗？例如：fn与f1到f12按键恢复原来的样子

按理来说OC应该不会修改的？如果真的是OC修改的，你可以在OC选择系统的界面那里选择 “清除nvram” 那一项（我忘记具体的英文了），然后应该就恢复了。

**Comment by aiyunyuner** [comment]
bios 应该是被修改过吧，在win10中，我的f1-f12的按键还是mac中的按键规则

**Comment by tonyleelyy** [comment]
> bios 应该是被修改过吧，在win10中，我的f1-f12的按键还是mac中的按键规则

我这边没这种情况，不清楚。
