### ISSUE TITLE
1060版的3579能用吗？

### ISSUE THREAD

**Issue by kayeung** [tonyleelyy/OpenCore-Hackintosh-Dell-G3-3579#15]
带type-c的那个版本，i7的

**Comment by kayeung** [comment]
还有oc的使用方法是怎样？是不是像三叶草那样直接复制到对应路径即可？

**Comment by tonyleelyy** [comment]
理论上除了type-c接口之外（我自己定制了USBPorts.kext），都是可用的，不过我没有测试过。

OC你直接复制到EFI，添加启动项就行，用法跟四叶草一样。

**Comment by kayeung** [comment]
我之前自己弄的clover10.15.1，type-c接口正常，如果我用了你的oc type-c不正常的话，替换我之前弄的clover里的USBPorts.kext，那应该可以的吧？

**Comment by tonyleelyy** [comment]
> 我之前自己弄的clover10.15.1，type-c接口正常，如果我用了你的oc type-c不正常的话，替换我之前弄的clover里的USBPorts.kext，那应该可以的吧？

可以

**Comment by kayeung** [comment]
好的，我去试试i

**Comment by prozyy** [comment]
你好，能否把你改好的支持Type-c的EFI发我一份，多谢，邮箱mail163_zyy@163.com

**Comment by kayeung** [comment]
> 你好，能否把你改好的支持Type-c的EFI发我一份，多谢，邮箱[mail163_zyy@163.com](mailto:mail163_zyy@163.com)

没有改成功，type-c to HDMI依然不起效

**Comment by prozyy** [comment]
> > 你好，能否把你改好的支持Type-c的EFI发我一份，多谢，邮箱[mail163_zyy@163.com](mailto:mail163_zyy@163.com)
> 
> 没有改成功，type-c to HDMI依然不起效

https://github.com/CerteKim/Dell-G3-3579-3779-Hackintosh-OpenCore
这个EFI支持 type-c 使用扩展坞 连接U盘正常，hdmi不行

**Comment by kayeung** [comment]
> > > 你好，能否把你改好的支持Type-c的EFI发我一份，多谢，邮箱[mail163_zyy@163.com](mailto:mail163_zyy@163.com)
> > 
> > 
> > 没有改成功，type-c to HDMI依然不起效
> 
> https://github.com/CerteKim/Dell-G3-3579-3779-Hackintosh-OpenCore
> 这个EFI支持 type-c 使用扩展坞 连接U盘正常，hdmi不行

type-c to HDMI对我来说重要一点，我要外接显示器

**Comment by prozyy** [comment]
> > > > 你好，能否把你改好的支持Type-c的EFI发我一份，多谢，邮箱[mail163_zyy@163.com](mailto:mail163_zyy@163.com)
> > > 
> > > 
> > > 没有改成功，type-c to HDMI依然不起效
> > 
> > 
> > https://github.com/CerteKim/Dell-G3-3579-3779-Hackintosh-OpenCore
> > 这个EFI支持 type-c 使用扩展坞 连接U盘正常，hdmi不行
> 
> type-c to HDMI对我来说重要一点，我要外接显示器

那个efi 只需要在 boot-args 里添加参数 agdpmod=vit9696 就可以type-c 转hdmi外接显示器了，亲测支持4k，方便的话辛苦把你微信号发我邮箱一下，方便交流，目前我这边intel wifi可以使用，蓝牙开启不了
