### ISSUE TITLE
dw1820a蓝牙无法使用

### ISSUE THREAD

**Issue by qewpqewp** [tonyleelyy/OpenCore-Hackintosh-Dell-G3-3579#16]
你好，我笔记本是g3 i7 8750h版的，用别人的i7版的efi的不能使用，用你的opencore版的可以完美引导，刚换了dw1820a，蓝牙无信息，识别不到，想问下你的acpi是否有为了适配ac9462而改动，导致别的蓝牙型号无法使用，谢谢

**Comment by tonyleelyy** [comment]
你要给你的网卡加驱动才能用的。。。

删除/OC/Kexts/ 下的IntelBluetooth两个驱动，删除itlwm.kext，修改config.plist，再自行添加关于你网卡的信息。

网上有很多关于你这个卡的驱动教程。
