### ISSUE TITLE
Pls help 

### ISSUE THREAD

**Issue by marcinkk** [tonyleelyy/OpenCore-Hackintosh-Dell-G3-3579#17]
Hey, how do you set the keys to adjust the screen brightness on a laptop keyboard ?? Right now it's fn + f12 and fn + key pause. My bootloader is opencore. In my laptop acer v3-371, the shortcut from adjusting the screen brightness on the keyboard is the shortcut fn + left arrow key and fn + arrow right key.

**Comment by tonyleelyy** [comment]
See https://github.com/daliansky/OC-little/tree/master/14-%E4%BA%AE%E5%BA%A6%E5%BF%AB%E6%8D%B7%E9%94%AE

Or just use a software in macOS: [Karabiner-Element](https://karabiner-elements.pqrs.org/)

**Comment by marcinkk** [comment]
Thank you for this tutorial.  Adds the acpidebug.kext file and the ssdt and patch files from the ssdt file to config.plist.  Restarts the system and press the shortcut fn + arrow right / left but in console nothing appears that I pressed these keys on the keyboard.

**Comment by tonyleelyy** [comment]
> Thank you for this tutorial. Adds the acpidebug.kext file and the ssdt and patch files from the ssdt file to config.plist. Restarts the system and press the shortcut fn + arrow right / left but in console nothing appears that I pressed these keys on the keyboard.

Honestly, it is a complicated job to do that patch. I can't figure it out for now. I personally recommend you to use [Karabiner-Element](https://karabiner-elements.pqrs.org/) as replacement.

**Comment by marcinkk** [comment]
I will try this program.

**Comment by tonyleelyy** [comment]
> I will try this program.

Good luck to you~😊
