### ISSUE TITLE
Battery Life!

### ISSUE THREAD

**Issue by DellG3** [tonyleelyy/OpenCore-Hackintosh-Dell-G3-3579#18]
I have successfully installed Mojave. However, the battery life on Win 10 would be around 6 hours. On Mojave, it's around 2.5 hours. Is the power management for the build fixed? Brother, how can I do it? I'm new to this stuff and would love to learn.

**Comment by tonyleelyy** [comment]
I have fixed the power management problem last month. There shouldn't be such a problem anymore.
BTW, I did it by using:
- SSDT-PLUG-_SB.PR00.aml (enable CPU power management)
- SSDT-NDGP_OFF.aml (block dGPU)

There are other files you can check:
- itlwm.kext
This is our WiFi driver, which is still in beta. It's known to use a lot of power even after WiFi connected. You can try to disable it first in config.plist to see if the battery life gets longer.

- IntelBluetoothFirmware.kext & IntelBluetoothInjector.kext
The Bluetooth driver. It might be unstable sometimes. Again, disable it in config.plist to see if the battery gets better.

- CPUFriend.kext & CPUFriendDataProvider.kext
Kexts for managing CPU frequency. You can build your own one by [one-key-cpufriend](https://github.com/stevezhengshiqi/one-key-cpufriend).

- USBPower.kext
USB patch for faster iPhone / iPad charging. Disable it in config.plist if you don't need it.

- See which app uses the most battery in your system.

**Comment by DellG3** [comment]
By the way, my CPU is i7 8750H. What should be the changes I have to make? Wi-Fi and Bluetooth work fine. However, the processor is at high frequency when charging (computer running idle with no apps). Can I generate my own CPU states by the above mentioned "one-key-cpufriend"?
And which guides have you followed to patch SSDTs?
Thanks!

**Comment by tonyleelyy** [comment]
If the CPU frequency is abnormal, then it should be the problem of CPUFriend.kext & CPUFriendDataProvider.kext. Use one-key-cpufriend to generate your kexts.

However, I'm not sure if my SSDT-PLUG-_SB.PR00.aml works for your i7 CPU.
See the guide here to check: [05-1-注入X86](https://github.com/daliansky/OC-little/tree/master/05-%E6%B3%A8%E5%85%A5%E8%AE%BE%E5%A4%87/05-1-%E6%B3%A8%E5%85%A5X86) (Sorry it is in Chinese)

**Comment by DellG3** [comment]
Thanks! one-key-cpufriend has reduced my CPU frequency. Now I got another issue. The Wi-Fi has suddenly stopped working after a reboot. I tried shut down too. No luck.
You have any issues with Wi-Fi in Catalina? How long is the battery life?

**Comment by tonyleelyy** [comment]
I have many issues with WiFi in Catalina...Sometimes it just doesn't work. But maybe you can try to reset nvram in OC.

Sorry, I don't know how long is the battery life. My battery is old and almost dead due to my heavy use.

**Comment by DellG3** [comment]
Thank you so much!
