### ISSUE TITLE
总结一些使用中发现的小问题

### ISSUE THREAD

**Issue by aidenmx** [tonyleelyy/OpenCore-Hackintosh-Dell-G3-3579#19]
首先非常感谢您做的这些工作，您的efi是我目前知道本机型最好的！😄不过在使用过程中依然遇到了一些小问题，可以参考一下
1. 休眠后有几率蓝牙无法工作
2. 引导菜单中的的win选项大部分时间无法正常启动，偶尔几次可以
3. 设置中的修改修饰键功能经常不起作用，有时却玄学的可以生效
4. 点击大写锁定键后大写指示灯常亮，无法关闭，这好像是使用了您在另一个issue中推荐的修改键盘映射的工具后才有的问题，之后卸载也无效
5.  蓝牙连接airpods后调节音频输出设备的界面会卡住无法调节，不过其他一切功能工作的都很正常

这些问题基本都不影响使用，有的和您应该也没有关系，所以不用很放在心上，在之后的更新中如果有机会的话可以顺便修复，或者可以告诉我解决的方法，我会尽我所能去做。最后再次感谢您做出的贡献，这是我第一次写issue，不有冒犯请见谅

**Comment by tonyleelyy** [comment]
非常开心得到了你的肯定：）也非常感谢你发现这些问题！

1. 蓝牙的驱动确实是有些问题，我自己的蓝牙鼠标很多时候都没法用，现在终于可以确定不是我的鼠标问题了哈哈哈。不过这个咱们只能等驱动作者完善了~
2. 引导菜单是指OC里面的那个吗？说实话我都不知道原来Windows是可以启动的hhh，比较推荐直接使用Windows自带的UEFI引导来启动，开机时按F12就可以选择了。OC引导Windows这个比较复杂，暂时没有打算去解决。
3. 修改修饰键这个我倒是没有这样的问题，我是将Win键和Alt键调换了，然后一直都是可以使用的。这个我有空研究一下。
4. 大小写灯的问题也困扰了我很久，我现在是更新了系统之后有可能会变正常，有些系统版本就会抽风，暂时不知道是OC的问题还是macOS的bug。你说的那个工具我还真没留意，我有空也去排查一下，非常感谢你打开了新思路！
5. 这个建议你看看自带的扬声器能否发声，有时候AppleALC会抽风不加载（驱动本身的缺陷），或许不是蓝牙而是AppleALC导致的，我的蓝牙耳机放在学校了，身边没有设备可以验证，之后会留意一下的！

真的非常感谢你的分享，给这个项目的完善提供了新思路！这也是我在Github的第一个正儿八经的项目，如果还有发现什么问题欢迎继续提出~非常感谢！

**Comment by aidenmx** [comment]
感谢你的回复！同时也很高兴能够帮助这个项目进步，这是我的荣幸😄
