### ISSUE TITLE
非常感谢你能为G3机型做出贡献

### ISSUE THREAD

**Issue by LingCore** [tonyleelyy/OpenCore-Hackintosh-Dell-G3-3579#2]
由衷感谢，希望你能做得更好。

**Comment by tonyleelyy** [comment]
> 由衷感谢，希望你能做得更好。

谢谢这位朋友，能帮到你是我的荣幸。
这台电脑也是我的生产力工具，所以我会一直更新的！
另外告诉你一个好消息，Intel的无线网卡今天已经有了很大进展，敬请期待！

**Comment by LingCore** [comment]
> > 由衷感谢，希望你能做得更好。
> 
> 谢谢这位朋友，能帮到你是我的荣幸。
> 这台电脑也是我的生产力工具，所以我会一直更新的！
> 另外告诉你一个好消息，Intel的无线网卡今天已经有了很大进展，敬请期待！

我已经看到了你更新了项目，但是我不知道如何使用此WiFi驱动，能提供一份略微详细的教程吗？

**Comment by tonyleelyy** [comment]
> > > 由衷感谢，希望你能做得更好。
> > 
> > 
> > 谢谢这位朋友，能帮到你是我的荣幸。
> > 这台电脑也是我的生产力工具，所以我会一直更新的！
> > 另外告诉你一个好消息，Intel的无线网卡今天已经有了很大进展，敬请期待！
> 
> 我已经看到了你更新了项目，但是我不知道如何使用此WiFi驱动，能提供一份略微详细的教程吗？

抱歉，昨天晚上使用WiFi的过程中出现很大问题（重启之后加载驱动还是无法使用），暂时还不知道怎么解决。

解决了之后我会立即提供教程。麻烦耐心等候。

**Comment by LingCore** [comment]
> > > > 由衷感谢，希望你能做得更好。
> > > 
> > > 
> > > 谢谢这位朋友，能帮到你是我的荣幸。
> > > 这台电脑也是我的生产力工具，所以我会一直更新的！
> > > 另外告诉你一个好消息，Intel的无线网卡今天已经有了很大进展，敬请期待！
> > 
> > 
> > 我已经看到了你更新了项目，但是我不知道如何使用此WiFi驱动，能提供一份略微详细的教程吗？
> 
> 抱歉，昨天晚上使用WiFi的过程中出现很大问题（重启之后加载驱动还是无法使用），暂时还不知道怎么解决。
> 
> 解决了之后我会立即提供教程。麻烦耐心等候。

好的，谢谢~

**Comment by tonyleelyy** [comment]
> > > > > 由衷感谢，希望你能做得更好。
> > > > 
> > > > 
> > > > 谢谢这位朋友，能帮到你是我的荣幸。
> > > > 这台电脑也是我的生产力工具，所以我会一直更新的！
> > > > 另外告诉你一个好消息，Intel的无线网卡今天已经有了很大进展，敬请期待！
> > > 
> > > 
> > > 我已经看到了你更新了项目，但是我不知道如何使用此WiFi驱动，能提供一份略微详细的教程吗？
> > 
> > 
> > 抱歉，昨天晚上使用WiFi的过程中出现很大问题（重启之后加载驱动还是无法使用），暂时还不知道怎么解决。
> > 解决了之后我会立即提供教程。麻烦耐心等候。
> 
> 好的，谢谢~

WiFi搞定啦！给出了教程，去试试吧~

**Comment by LingCore** [comment]
> > > > > > 由衷感谢，希望你能做得更好。
> > > > > 
> > > > > 
> > > > > 谢谢这位朋友，能帮到你是我的荣幸。
> > > > > 这台电脑也是我的生产力工具，所以我会一直更新的！
> > > > > 另外告诉你一个好消息，Intel的无线网卡今天已经有了很大进展，敬请期待！
> > > > 
> > > > 
> > > > 我已经看到了你更新了项目，但是我不知道如何使用此WiFi驱动，能提供一份略微详细的教程吗？
> > > 
> > > 
> > > 抱歉，昨天晚上使用WiFi的过程中出现很大问题（重启之后加载驱动还是无法使用），暂时还不知道怎么解决。
> > > 解决了之后我会立即提供教程。麻烦耐心等候。
> > 
> > 
> > 好的，谢谢~
> 
> WiFi搞定啦！给出了教程，去试试吧~

cool~

**Comment by LingCore** [comment]
> > > > > > 由衷感谢，希望你能做得更好。
> > > > > 
> > > > > 
> > > > > 谢谢这位朋友，能帮到你是我的荣幸。
> > > > > 这台电脑也是我的生产力工具，所以我会一直更新的！
> > > > > 另外告诉你一个好消息，Intel的无线网卡今天已经有了很大进展，敬请期待！
> > > > 
> > > > 
> > > > 我已经看到了你更新了项目，但是我不知道如何使用此WiFi驱动，能提供一份略微详细的教程吗？
> > > 
> > > 
> > > 抱歉，昨天晚上使用WiFi的过程中出现很大问题（重启之后加载驱动还是无法使用），暂时还不知道怎么解决。
> > > 解决了之后我会立即提供教程。麻烦耐心等候。
> > 
> > 
> > 好的，谢谢~
> 
> WiFi搞定啦！给出了教程，去试试吧~

我刚刚测试了，的确是可以使用了，但是就如同那个作者所说的，网速非常的慢，大约只有10分之1的网速，而且容易断连？我也不知道怎么形容，可能离正常使用还有一段时间。不过，谢谢你了~

**Comment by tonyleelyy** [comment]
> > > > > > > 由衷感谢，希望你能做得更好。
> 
> > > > > > 
> 
> > > > > > 
> 
> > > > > > 谢谢这位朋友，能帮到你是我的荣幸。
> 
> > > > > > 这台电脑也是我的生产力工具，所以我会一直更新的！
> 
> > > > > > 另外告诉你一个好消息，Intel的无线网卡今天已经有了很大进展，敬请期待！
> 
> > > > > 
> 
> > > > > 
> 
> > > > > 我已经看到了你更新了项目，但是我不知道如何使用此WiFi驱动，能提供一份略微详细的教程吗？
> 
> > > > 
> 
> > > > 
> 
> > > > 抱歉，昨天晚上使用WiFi的过程中出现很大问题（重启之后加载驱动还是无法使用），暂时还不知道怎么解决。
> 
> > > > 解决了之后我会立即提供教程。麻烦耐心等候。
> 
> > > 
> 
> > > 
> 
> > > 好的，谢谢~
> 
> > 
> 
> > WiFi搞定啦！给出了教程，去试试吧~
> 
> 
> 
> 我刚刚测试了，的确是可以使用了，但是就如同那个作者所说的，网速非常的慢，大约只有10分之1的网速，而且容易断连？我也不知道怎么形容，可能离正常使用还有一段时间。不过，谢谢你了~

嘿嘿，能连上已经很好了，咋们也不是什么专家，耐心等候作者大神的更新吧～能连上证明方向已经对了。

不用客气的，这个issue我下午晚点就先关闭了，感谢你的使用～有什么问题欢迎继续交流哦！

**Comment by LingCore** [comment]
> 这个issue我下午晚点就先关闭了，感谢你的使用～有

okey~~
