### ISSUE TITLE
关于itlwm

### ISSUE THREAD

**Issue by lcx397** [tonyleelyy/OpenCore-Hackintosh-Dell-G3-3579#20]
首先感谢你为3579做的efi
其次有个问题请教一下，当efi在u盘里的时候，itlwm可以正常用。
我把efi放到自己的固态里，网卡驱动不加载。
请问有解决办法吗？

**Comment by tonyleelyy** [comment]
首先不要从Windows重启到macOS，需要断电再开机直接进macOS才能用。

然后如果再不行的话清除一遍nvram就好了

**Comment by lcx397** [comment]
感谢大佬，已解决
