### ISSUE TITLE
请问有办法让OC引导windows吗？

### ISSUE THREAD

**Issue by CalvinXu17** [tonyleelyy/OpenCore-Hackintosh-Dell-G3-3579#21]
我用OC引导就蓝屏。还有就是网卡换成DW1820A要用蓝牙的话，这里的USBPorts有点问题导致蓝牙驱动识别不了，因为DW1820A的蓝牙是接在USB上的，之前一直用的Clover，为了升级10.15换成了你的OC，把USB换成以前Clover里的蓝牙就正常了。。

**Comment by CalvinXu17** [comment]
还是得先感谢一下你提供的帮助，不然我用以前的Clover就没有办法升级系统

**Comment by tonyleelyy** [comment]
想要让OC可以引导Windows的话，最简单安全的方法是使用远景大神魔改的OC：[链接](http://bbs.pcbeta.com/forum.php?mod=viewthread&tid=1838814)

其实我的SSDT补丁都已经为系统识别做了适配，应该修改一些设置就可以引导Windows，不过我感觉没必要，直接开机按F12选择自带的UEFI引导就好了，省事多了，暂时不打算研究。

另外感谢您对USB的问题反馈，我有空会研究一下的！最近学业比较繁忙。。。

**Comment by CalvinXu17** [comment]
> 想要让OC可以引导Windows的话，最简单安全的方法是使用远景大神魔改的OC：[链接](http://bbs.pcbeta.com/forum.php?mod=viewthread&tid=1838814)
> 
> 其实我的SSDT补丁都已经为系统识别做了适配，应该修改一些设置就可以引导Windows，不过我感觉没必要，直接开机按F12选择自带的UEFI引导就好了，省事多了，暂时不打算研究。
> 
> 另外感谢您对USB的问题反馈，我有空会研究一下的！最近学业比较繁忙。。。

好的，非常感谢！

**Comment by CalvinXu17** [comment]
刚刚试了下把Booter -> Quirks中的SyncRuntimePermissions打上勾就可以引导win10了，参照的远景的帖子http://bbs.pcbeta.com/viewthread-1851965-1-1.html

**Comment by tonyleelyy** [comment]
> 刚刚试了下把Booter -> Quirks中的SyncRuntimePermissions打上勾就可以引导win10了，参照的远景的帖子http://bbs.pcbeta.com/viewthread-1851965-1-1.html

赞！使用稳定的话我下个版本加上，带上你的名字

**Comment by CalvinXu17** [comment]
> > 刚刚试了下把Booter -> Quirks中的SyncRuntimePermissions打上勾就可以引导win10了，参照的远景的帖子http://bbs.pcbeta.com/viewthread-1851965-1-1.html
> 
> 
> 
> 赞！使用稳定的话我下个版本加上，带上你的名字

共同交流研究😁DW1820A网卡蓝牙可以试试我这个USBPorts 链接: https://pan.baidu.com/s/1TPKzaA0kuVNpQi-539FwVw 提取码: 4byw

**Comment by tonyleelyy** [comment]
> 共同交流研究😁DW1820A网卡蓝牙可以试试我这个USBPorts 链接: https://pan.baidu.com/s/1TPKzaA0kuVNpQi-539FwVw 提取码: 4byw

请问能否提供一下 Hackintool 里面USB界面的截图？我想看看蓝牙是哪个端口

**Comment by CalvinXu17** [comment]
> > 共同交流研究😁DW1820A网卡蓝牙可以试试我这个USBPorts 链接: https://pan.baidu.com/s/1TPKzaA0kuVNpQi-539FwVw 提取码: 4byw
> 
> 请问能否提供一下 Hackintool 里面USB界面的截图？我想看看蓝牙是哪个端口

<img width="580" alt="1" src="https://user-images.githubusercontent.com/50015746/85871867-97d4b880-b801-11ea-968d-bb0fdb23588d.png">
<img width="652" alt="2" src="https://user-images.githubusercontent.com/50015746/85871886-9dca9980-b801-11ea-90ea-1df0c123173e.png">

**Comment by tonyleelyy** [comment]
感谢，我会在将来的版本修复USB问题。
