### ISSUE TITLE
ax200蓝牙

### ISSUE THREAD

**Issue by baobaodeya** [tonyleelyy/OpenCore-Hackintosh-Dell-G3-3579#22]
因为一些原因我的网卡换成了ax200，我发现一直驱动不了蓝牙，我的设置里甚至连蓝牙图标都无。
我尝试自己换了IntelBluetoothFirmware.kext和IntelBluetoothInjector.kext也是同样情况。

**Comment by tonyleelyy** [comment]
我不清楚IntelBluetoothFirmware.kext是否支持ax200的蓝牙。（我这个EFI的驱动肯定不支持，我自己精简了其他型号的驱动）
如果支持的话，那一般是USBPorts的问题，先换用USBInjectAll吧。你也可以自己定制一下USB试试。

**Comment by baobaodeya** [comment]
okay,这就去研究usb
