### ISSUE TITLE
请问这个是直接3579本机自带的英特尔无线网卡吗

### ISSUE THREAD

**Issue by GUO1115** [tonyleelyy/OpenCore-Hackintosh-Dell-G3-3579#23]

**Comment by tonyleelyy** [comment]
我配置表写得清清楚楚，不会看？

**Comment by GUO1115** [comment]
我的3579是AC9462的网卡 貌似还不能驱动

**Comment by tonyleelyy** [comment]
蓝牙不行就清除nvram，WiFi要自己在info.plist填WiFi账号密码

**Comment by zgpio** [comment]
>  WiFi要自己在info.plist填WiFi账号密码

请问填了多个wifi账号密码之后如何选择不同的wifi

**Comment by zgpio** [comment]
我发现了heliport

**Comment by tonyleelyy** [comment]
> 我发现了heliport

是的，现在应该比较完美了～
