### ISSUE TITLE
There was a shutdown problem!Please help me！

### ISSUE THREAD

**Issue by 13371027447** [tonyleelyy/OpenCore-Hackintosh-Dell-G3-3579#24]
My dear friend
I just started learning hackintosh . The first installation was successful some time ago. Clover was used at that time. At that time, there was a shutdown problem. However, I made a big mistake in the process of solving the problem, which led to the failure to boot Mac OS when using clover. I have no idea. So I tried your OC EFI to boot. I finally succeeded! Thank you very much! However, it still can't be turned off at present. After the shutdown, the fan still works. The same is true of hibernation mode, and it doesn't wake up the computer. Don't know what's the reason, drive? BIOS？But，no matter what method I use, including changing the boot mode, I can't solve this problem。I really have no way. I want to ask you for help.I really hope you can reply me.My computer is the same as yours. My BIOS is the latest version.

**Comment by 13371027447** [comment]
And the BIOS has been set according to what you said

**Comment by MM-CY-2333** [comment]
这个问题我也遇到了，大概两个星期之前，一开始以为是没有配置好OC,后来格式化硬盘重装成了win10，关机后风扇依然停不下来，除非长按电源键断电，现在电脑在戴尔售后，已经一个星期了。工作人员说已经修好，具体原因等取机时候再详细询问。

**Comment by 13371027447** [comment]
> 这个问题我也遇到了，大概两个星期之前，一开始以为是没有配置好OC，后来格式化硬盘重装变成win10，关机后风扇依然停不下来，除非长按电源键断电，现在电脑在戴尔售后，已经一个星期了。工作人员说已经修好，具体原因等取机时候再详细询问。

好嘞 还请您事后告知！提前感谢了 老哥！

**Comment by tonyleelyy** [comment]
这个问题我之前也听其他老哥说了，真的很奇怪，说实话到现在为止我还没有一个很好的解决方法。

唯一的解决方法是在远景上看到的，拿个U盘，安装Ubuntu，然后不关机的问题就解决了，就是这么神奇哈哈哈，两位老哥可以试试！

**Comment by tonyleelyy** [comment]
如果我没记错的话，之前已经有两个哥们遇到这个问题了，都是用Ubuntu大法解决的哈哈哈。

**Comment by 13371027447** [comment]
这？啊？就把Ubuntu系统装到一个U盘就可以吗...这什么操作...

**Comment by 13371027447** [comment]
> 如果我没记错的话，之前已经有两个哥们遇到这个问题了，都是用Ubuntu大法解决的哈哈哈。

老哥还能找到那个帖子吗...我去试试....

**Comment by tonyleelyy** [comment]
> 这？啊？就把Ubuntu系统装到一个U盘就可以吗...这什么操作...

不是把系统装到U盘里，是像你安装macOS那样把Ubuntu的安装镜像刻录进去，然后正儿八经地安装一遍。远景的帖子我找不到了，案例可以看issue [#14](https://github.com/tonyleelyy/OpenCore-Hackintosh-Dell-G3-3579/issues/14)。

**Comment by 13371027447** [comment]
> > 这？啊？就把Ubuntu系统装到一个U盘就可以吗...这什么操作...
> 
> 不是把系统装到U盘里，是像你安装macOS那样把Ubuntu的安装写入刻录进去，然后正儿八经地安装一遍。远景的帖子我找到了，案例可以看问题[＃14](https://github.com/tonyleelyy/OpenCore-Hackintosh-Dell-G3-3579/issues/14)。

好的 我这尝试安装一下 可是我的MAC是在固态的 Ubuntu安装到机械不知道有用不 我先去试试吧 谢谢！！

**Comment by 13371027447** [comment]
对了 老哥
求帖子链接！感谢

**Comment by 13371027447** [comment]
> > 这？啊？就把Ubuntu系统装到一个U盘就可以吗...这什么操作...
> 
> 不是把系统装到U盘里，是像你安装macOS那样把Ubuntu的安装写入刻录进去，然后正儿八经地安装一遍。远景的帖子我找到了，案例可以看问题[＃14](https://github.com/tonyleelyy/OpenCore-Hackintosh-Dell-G3-3579/issues/14)。

对了老哥
求帖子链接！感谢

**Comment by 13371027447** [comment]
> > 这？啊？就把Ubuntu系统装到一个U盘就可以吗...这什么操作...
> 
> 不是把系统装到U盘里，是像你安装macOS那样把Ubuntu的安装写入刻录进去，然后正儿八经地安装一遍。远景的帖子我找到了，案例可以看问题[＃14](https://github.com/tonyleelyy/OpenCore-Hackintosh-Dell-G3-3579/issues/14)。

对了老哥
求帖子链接！感谢

**Comment by tonyleelyy** [comment]
> > > 这？啊？就把Ubuntu系统装到一个U盘就可以吗...这什么操作...
> 
> > 
> 
> > 不是把系统装到U盘里，是像你安装macOS那样把Ubuntu的安装写入刻录进去，然后正儿八经地安装一遍。远景的帖子我找到了，案例可以看问题[＃14](https://github.com/tonyleelyy/OpenCore-Hackintosh-Dell-G3-3579/issues/14)。
> 
> 
> 
> 对了老哥
> 
> 求帖子链接！感谢

打错字了不好意思...是我没找到hhhh

**Comment by 13371027447** [comment]
hhhh好的好的

**Comment by 13371027447** [comment]
装了Ubuntu立马好了...这也太神奇了吧...而且我安装的还有错误进不去系统，就可以正常关机了，休眠也正常了。真的玄学，感谢两位老哥的指导帮助啊！感谢！感谢！感谢！ 
感谢tonyleelyy老哥的奉献精神！

**Comment by tonyleelyy** [comment]
> 装了Ubuntu立马好了...这也太神奇了吧...而且我安装的还有错误进不去系统，就可以正常关机了，休眠也正常了。真的玄学，感谢两位老哥的指导帮助啊！感谢！感谢！感谢！ 
> 
> 感谢tonyleelyy老哥的奉献精神！

恭喜恭喜啊！也感谢你的汇报，之后有发现什么问题也尽管说！

**Comment by MM-CY-2333** [comment]
今天把电脑取回来了，可惜没见到维修师傅。前台接待说换了个主板...问具体是哪里的问题接待也不懂，没得到更多的信息...大家再遇见这个问题还是用乌班图大法解决吧。
然后现在又装上10.15.5了，这次很完美，哈哈哈，感谢老哥的EFI

**Comment by tonyleelyy** [comment]
> 今天把电脑取回来了，可惜没见到维修师傅。前台接待说换了个主板...问具体是哪里的问题接待也不懂，没得到更多的信息...大家再遇见这个问题还是用乌班图大法解决吧。
> 
> 然后现在又装上10.15.5了，这次很完美，哈哈哈，感谢老哥的EFI

哈哈哈哈恭喜恭喜，下次还是Ubuntu大法好～
