### ISSUE TITLE
DW1820A 无法驱动，登陆界面卡死

### ISSUE THREAD

**Issue by kayeung** [tonyleelyy/OpenCore-Hackintosh-Dell-G3-3579#25]
我更换了1820A，现在是10.15.6，蓝牙不工作，所以我参考了小兵给1820A修复蓝牙的教程，可是教程走完后，无法引导系统，卡在多段oc开头的代码。我把config.plist换回您原本的就正常开机，请问下这该怎么解决？？

**Comment by tonyleelyy** [comment]
> 我更换了1820A，现在是10.15.6，蓝牙不工作，所以我参考了小兵给1820A修复蓝牙的教程，可是教程走完后，无法引导系统，卡在多段oc开头的代码。我把config.plist换回您原本的就正常开机，请问下这该怎么解决？？

蓝牙不工作其实是USBPorts的问题，我看看今晚或者明天推一个修复版本。

另外修改config.plist需要使用Propertree。oc开头的错误代码应该就是软件不合适或者有些内容填得不规范了，我没有1820A，不过看看能不能试着帮你修复一下吧～

**Comment by kayeung** [comment]
好的谢谢！既然你在修复，我顺便提个小问题吧，wifi不能搜全5G的信号，我家里的5g搜不到，但是隔壁的5g就能搜到很奇怪！我尝试改信道，试遍了一样搜不到

**Comment by tonyleelyy** [comment]
> 好的谢谢！既然你在修复，我顺便提个小问题吧，wifi不能搜全5G的信号，我家里的5g搜不到，但是隔壁的5g就能搜到很奇怪！我尝试改信道，试遍了一样搜不到

这有点奇怪啊...把信道改成自动试试，我之前帮别人弄就是这么修复的。不行的话我就不知道了...

**Comment by tonyleelyy** [comment]
我刚推了一个修复USB的版本，你可以先试试能不能用，我等会再帮你另写一个config.plist

**Comment by tonyleelyy** [comment]
我添加了小兵博客里的那三个驱动，删除了Intel网卡的驱动，然后在config.plist注入了驱动信息，你看看行不行吧~（WiFi我没动，先默认你已经能驱动WiFi了）

[EFI_for_DW1820A.zip](https://github.com/tonyleelyy/OpenCore-Hackintosh-Dell-G3-3579/files/4975676/EFI_for_DW1820A.zip)

**Comment by kayeung** [comment]
> 驱动

失败！
1.开机没有选择启动系统的菜单，直接是苹果logo
2.logo一会后，到输入密码的页面，输入密码后卡死（正常是走进度条）

**Comment by kayeung** [comment]
感觉是config.plist有问题

**Comment by tonyleelyy** [comment]
不好意思，改少了一个地方，你替换这个。

[config.zip](https://github.com/tonyleelyy/OpenCore-Hackintosh-Dell-G3-3579/files/4975724/config.zip)

**Comment by kayeung** [comment]
能选择系统了，但是仍然输入密码后卡死

**Comment by tonyleelyy** [comment]
> 能选择系统了，但是仍然输入密码后卡死

用我release的那个试试：https://github.com/tonyleelyy/OpenCore-Hackintosh-Dell-G3-3579/releases/tag/v3.2
先不驱动网卡看看会不会卡。

感觉有可能是驱动问题

**Comment by Loading39** [comment]
还是不行，一样卡死

**Comment by kayeung** [comment]
能正常进入系统，但是输入密码后有卡死一小段，10多秒后才出来进度条。
进入系统后仍然没有蓝牙，只有Wi-Fi

**Comment by tonyleelyy** [comment]
有尝试屏蔽针脚吗？我在网上查到这样卡死，有可能是兼容性问题，有的机器需要屏蔽针脚。

**Comment by kayeung** [comment]
已经屏蔽了，之前clover都能正常用

**Comment by tonyleelyy** [comment]
这张卡太棘手了，待我再研究一下

**Comment by kayeung** [comment]
烦就烦在10.15.3clover一切可用，昨天重装10.15.6，之前的clover用不了，连小兵自带的也用不了，卡在啰嗦模式里，只有您的oc能用

**Comment by tonyleelyy** [comment]
[EFI_for_DW1820A_2.zip](https://github.com/tonyleelyy/OpenCore-Hackintosh-Dell-G3-3579/files/4975883/EFI_for_DW1820A_2.zip)
我添加了一个AirportBrcmFixFixup，你试试看行不行

**Comment by kayeung** [comment]
Config.plist 有改好吗？

**Comment by tonyleelyy** [comment]
> Config.plist 有改好吗？

有的

**Comment by kayeung** [comment]
> [EFI_for_DW1820A_2.zip](https://github.com/tonyleelyy/OpenCore-Hackintosh-Dell-G3-3579/files/4975883/EFI_for_DW1820A_2.zip)
> 我添加了一个AirportBrcmFixFixup，你试试看行不行

不行，输入密码后又卡死

**Comment by kayeung** [comment]
要不留个扣扣？这样联系不太方便

**Comment by tonyleelyy** [comment]
wx：lyy505582275

**Comment by tonyleelyy** [comment]
> 要不留个扣扣？这样联系不太方便

wx：tonyleelyy

**Comment by tonyleelyy** [comment]
> 要不留个扣扣？这样联系不太方便

QQ: 505582275

**Comment by L0gIc301** [comment]
刚刚准备下单1820A，看了一下评论，暂时放弃，感谢博主的EFI，终于在版本末期从10.14.6升到10.15.6

**Comment by tonyleelyy** [comment]
> 刚刚准备下单1820A，看了一下评论，暂时放弃，感谢博主的EFI，终于在版本末期从10.14.6升到10.15.6

这个卡除非动手能力很强，不然真的不太推荐，非常容易踩雷...
