### ISSUE TITLE
OC0.6.0有的，支持big sur

### ISSUE THREAD

**Issue by VersionZKP2356** [tonyleelyy/OpenCore-Hackintosh-Dell-G3-3579#27]
https://gitee.com/shuiyunxc/OpenCore/releases
OC0.6.0

**Comment by tonyleelyy** [comment]
确实有，但如果我一直用daily build的oc测试版，工作量就太大了...隔几天就要重新检查config...而且现在bug还很多，感觉没必要硬上Big Sur

**Comment by tonyleelyy** [comment]
如果有兴趣的话，可以自己试着适配一下~不难的

**Comment by VersionZKP2356** [comment]
自己弄了一个，尝鲜big sur，结果直接卡内核

**Comment by VersionZKP2356** [comment]
卡内核的问题我一直不会解决，直接要么换efi，要么换安装的MacOS版本

**Comment by tonyleelyy** [comment]
卡内核可能是有部分驱动没更新

**Comment by VersionZKP2356** [comment]
哦，我确实有些没更新，它刚开始跑码不到一秒钟就卡了

**Comment by tonyleelyy** [comment]
https://github.com/MicalShow/DELL-G3-3579-Opencore-Big-Sur

用这个吧，有朋友已经适配好了

**Comment by VersionZKP2356** [comment]
我也想改你的，但没成功，我是dw1820a网卡，还得弄驱动
我还是用这位的吧https://github.com/CerteKim/Dell-G3-3579-3779-Hackintosh-OpenCore/tree/bigsur

**Comment by VersionZKP2356** [comment]
加个Windows引导就好了
