### ISSUE TITLE
10.13.6 声卡不能驱动

### ISSUE THREAD

**Issue by VersionZKP2356** [tonyleelyy/OpenCore-Hackintosh-Dell-G3-3579#28]
我用你的OC引导安装了10.13.6系统，因为我的网卡是DW1820A，所以我在config.plist里删除了关于Intel网卡的驱动，添加了博通网卡驱动。进系统后，网卡没有问题，但是声卡却检测不出来，在hackintool里能看到声卡的pci地址，但在音频里看不到。我看你的layout-ID设的是15对吧，我改成11也没用，怎么办

**Comment by tonyleelyy** [comment]
1. 多次重启系统。AppleALC本来就很容易掉驱动。
2. 重建缓存
3. 清除nvram

**Comment by VersionZKP2356** [comment]
哦，我一会先试试重建缓存，因为我在换你的OC之前把N卡开起来了，然后HDMI的声卡和内建声卡冲突，再把N卡禁了，结果就没声卡了。我是不是要把Layout-ID改回15？

**Comment by VersionZKP2356** [comment]
怎么重建缓存呀

**Comment by tonyleelyy** [comment]
> 怎么重建缓存呀

用kext utility

**Comment by tonyleelyy** [comment]
> 哦，我一会先试试重建缓存，因为我在换你的OC之前把N卡开起来了，然后HDMI的声卡和内建声卡冲突，再把N卡禁了，结果就没声卡了。我是不是要把Layout-ID改回15？

你成功驱动N卡了？

**Comment by VersionZKP2356** [comment]
没......它显示的是NVIDIA Chips Model

**Comment by VersionZKP2356** [comment]
就因为作死把N卡开起来（不能说驱动了）结果就这样了。我用kext utility重建缓存了，结果还没用

**Comment by tonyleelyy** [comment]
> 哦，我一会先试试重建缓存，因为我在换你的OC之前把N卡开起来了，然后HDMI的声卡和内建声卡冲突，再把N卡禁了，结果就没声卡了。我是不是要把Layout-ID改回15？

LayoutID本来就是15，都有这么多朋友测试过了，不会错的

**Comment by VersionZKP2356** [comment]
我更改了一下，我之前用的oc声卡那一项有一堆选项，而你这个只有个Layout-ID

**Comment by VersionZKP2356** [comment]
![image](https://user-images.githubusercontent.com/62052278/89755340-ad801200-db11-11ea-8ff2-8ed282eef145.png)
我做了一些修改，但是现在没时间测试

**Comment by VersionZKP2356** [comment]
之前只有个Layout-ID，其他的AAPL,DEVICE-TYPE,HDA-GFX和MODEL都是我自己加的

**Comment by tonyleelyy** [comment]
> 我更改了一下，我之前用的oc声卡那一项有一堆选项，而你这个只有个Layout-ID

删掉是因为这些都是不必要的...一个layoutid就够了

**Comment by VersionZKP2356** [comment]
那我等有时间了试一试看看能不能用

**Comment by VersionZKP2356** [comment]
好了，问题已经解决，在引导参数里添加alcid=15就好了，然后我又加了个brcm-country=#a,目前一切正常
