### ISSUE TITLE
完整的文件

### ISSUE THREAD

**Issue by hackerschen** [tonyleelyy/OpenCore-Hackintosh-Dell-G3-3579#3]
我Dell_G3579 8代i5
使用你老版的boot+新的oc引导时出现windows start failed .... firmware..的
导致无法引导，之类的情况，可能是bios没有设置好，clover引导正常
求大神提供完整的文件，或者求大神写一篇博客 ，oc引导过程，小白求教

**Comment by tonyleelyy** [comment]
啊，请不要使用我的boot，每台电脑的那个文件应该都是不同的。

并且我的OC现在暂时不支持Windows引导，因为涉及到改名，将来也不会支持Windows。还请使用原生Windows的引导来启动Windows。

我完整的文件提供给你吧，不知道能不能帮到你。
[EFI.zip](https://github.com/tonyleelyy/OpenCore-Hackintosh-Dell-G3-3579/files/4482013/EFI.zip)

如果你的EFI已经损坏了的话，使用PE进行修复。

另外，很巧的是，我真的有一篇OC引导教程在写，不过博客现在在走备案流程，教程也还没完工，暂时还请稍等一下。应该快OK了，可以关注一下，地址 tonyleelyy.top。

感谢你的留言。

**Comment by hackerschen** [comment]
原谅我不是太懂，新手入门， 期待教程

**Comment by hackerschen** [comment]
大神加油

**Comment by tonyleelyy** [comment]
不是大神，咱们一起学习~
