### ISSUE TITLE
Stuck on Apple logo

### ISSUE THREAD

**Issue by narindraditantyo** [tonyleelyy/OpenCore-Hackintosh-Dell-G3-3579#30]
I can't even boot to my desktop after updating to version 4.0 with OpenCore 0.6.1
Any solution?

**Comment by tonyleelyy** [comment]
> I can't even boot to my desktop after updating to version 4.0 with OpenCore 0.6.1
> 
> Any solution?

OC 0.6.1 hasn't been tested yet.
You should use Release [v4.0](https://github.com/tonyleelyy/OpenCore-Hackintosh-Dell-G3-3579/releases/tag/v4.0) which is still in OC 0.6.0

**Comment by narindraditantyo** [comment]
I revert back to v4.0 and its stable again. Thanks!

**Comment by tonyleelyy** [comment]
Fixed issue with the newest release v4.1~Thanks!
