### ISSUE TITLE
[ASK] RAM upgrade

### ISSUE THREAD

**Issue by narindraditantyo** [tonyleelyy/OpenCore-Hackintosh-Dell-G3-3579#31]
Are there any additional step after I upgrade my RAM from 8GB to 12GB (8+4)?

**Comment by tonyleelyy** [comment]
> Are there any additional step after I upgrade my RAM from 8GB to 12GB (8+4)?

Nope~

**Comment by narindraditantyo** [comment]
Okay, thanks for the answer! Keep up the good work 👍🏻

**Comment by tonyleelyy** [comment]
You are welcome~
