### ISSUE TITLE
请问使用博通网卡该如何修改这个引导文件呢？

### ISSUE THREAD

**Issue by isoulgh** [tonyleelyy/OpenCore-Hackintosh-Dell-G3-3579#34]
我在文件里添加三个驱动文件，并config里加了配置，却无法引导，卡在苹果标志界面

**Comment by tonyleelyy** [comment]
请向启动参数里添加-v，看看到底是哪个驱动出错了。

**Comment by isoulgh** [comment]
感谢你的建议，我按照错误提示修复了引导问题，但还有一个使用随航的问题，可以搜索到ipad，但是连接错误，显示32002错误，请问我该怎么解决呢？

**Comment by tonyleelyy** [comment]
目前Airportitlwm尚不支持无线随航，请等待开发者开发。

**Comment by isoulgh** [comment]
感谢你的解答，由于我已经更换了博通网卡，结合我网上的搜索，成功解决了这些问题
