### ISSUE TITLE
请问我该如何修改引导文件才能使用雷电接口呢？

### ISSUE THREAD

**Issue by isoulgh** [tonyleelyy/OpenCore-Hackintosh-Dell-G3-3579#35]
请问我该如何修改引导文件才能使用雷电接口呢？添加了IOElectrity驱动试了一下，但是没有变化。无法使用雷电接口，仅可以给外接设备充电，不能传输数据。

**Comment by tonyleelyy** [comment]
重新定制USBPorts.kext试试
