### ISSUE TITLE
Opencore works perfectly on Catalina but not on High Sierra

### ISSUE THREAD

**Issue by porkCupine** [tonyleelyy/OpenCore-Hackintosh-Dell-G3-3579#36]
Installing Catalina on the Dell G3 3579 (8300H, 1050) was flawless. But High Sierra had issues. Kexts did not seem to load (UHD 630 has 7mb VRAM, airportitlwm not working, etc. I think this was a kernel panic but I'm not so sure).

I did this process to download High Sierra on the MacBookPro 15,1 SMBIOS: I moved the SSD to a real MacBook Pro and then downloaded High Sierra there. The SSD was then moved to the Dell. I used your EFI with -no_compat_check.

What should I do/try now?

Edit: Also, which SSDT should I modify to use dGPU in 10.13.6?

**Comment by tonyleelyy** [comment]
1. Try to delete Airportitlwm.kext from /kexts and config.plist
2. SSDT-NDGP_OFF.aml

**Comment by porkCupine** [comment]
Hi, I'll have to try it some time next week. But for the meantime, do you know of any reason why high sierra might not work? I've already tried changing to MBP 14,3 SMBIOS, -no_compat_check, and changing AAPL,ig-platform-id

**Comment by tonyleelyy** [comment]
> Hi, I'll have to try it some time next week. But for the meantime, do you know of any reason why high sierra might not work? I've already tried changing to MBP 14,3 SMBIOS, -no_compat_check, and changing AAPL,ig-platform-id

Don't konw why it doesn't work. But maybe you can try my older EFIs which OC have not changed the kexts inject method.
Use v3.0 or even v2.0

**Comment by porkCupine** [comment]
Unfortunately these suggestions didn't work. Thanks for your help anyway. I'm marking this as resolved because I won't have time for this for the foreseeable future
