### ISSUE TITLE
[ASK] Nvidia Webdriver Support for Catalina

### ISSUE THREAD

**Issue by narindraditantyo** [tonyleelyy/OpenCore-Hackintosh-Dell-G3-3579#37]
Hi, I found a forum thread that talks about Nvidia Webdriver working on Catalina (https://amd-osx.com/forum/viewtopic.php?t=9332). So, is it possible to use the same method to activate the HDMI output?

**Comment by narindraditantyo** [comment]
I don't think that hardware acceleration is enabled, but at least can it display output on the second screen through HDMI?

**Comment by tonyleelyy** [comment]
Can't be sure... but macOS with no acceleration is a nightmare.
