### ISSUE TITLE
Your computer restarted because of a problem!

### ISSUE THREAD

**Issue by rahultah** [tonyleelyy/OpenCore-Hackintosh-Dell-G3-3579#38]
Whenever I install/upgrade the macos catalina to big sur stable i get a message after installing and during boot "your computer restarted because of a problem" and is stuck in loop

**Comment by StevenKim523** [comment]
So do I. May be because of the version of OpenCore. But it haven't be updated yet.

**Comment by tonyleelyy** [comment]
Use [release v4.1](https://github.com/tonyleelyy/OpenCore-Hackintosh-Dell-G3-3579/releases/tag/v4.1) instead.
I will look into this issue in a few days. Thanks!

**Comment by rahultah** [comment]
Same issue with release 4.1 also. The same thing is happening with this 4.1

**Comment by tonyleelyy** [comment]
I might have fixed this problem. Please try this EFI and give me some feedback.
[v4.3 beta.zip](https://github.com/tonyleelyy/OpenCore-Hackintosh-Dell-G3-3579/files/5571630/v4.3.beta.zip)
I personally fresh installed Big Sur again, and found no problem any more.

Huge thanks to you guys!

**Comment by StevenKim523** [comment]
Thank you very much! Without your efforts, people with this laptop can not enjoy the hackintosh! :)

**Comment by rahultah** [comment]
Thanks a lot. This EFI works just fine. Really appreaciate your work.
