### ISSUE TITLE
How Can I install macOS using it?

### ISSUE THREAD

**Issue by Ravid-Levy** [tonyleelyy/OpenCore-Hackintosh-Dell-G3-3579#39]
I have g3 3579 i5 with 1050
How can I use it for install macos?
Can you guide me?

My phone is

**Comment by tonyleelyy** [comment]
https://dortania.github.io/OpenCore-Install-Guide/
YouTube video:
https://www.youtube.com/watch?v=eUnVzJsINCI

All you need to do:
1. Make an macOS installation USB drive
2. Put my EFI (download in my release page)into the EFI partition on your USB drive.
3. Add EFI/Boot/BOOTx64.efi to your boot sequence in BIOS
4. Boot and install macOS

**Comment by Ravid-Levy** [comment]
it required from me acess to the internet and I dont see any wifi driver inside..

**Comment by Ravid-Levy** [comment]
How can I change the lang into english? it is in Chinese or something like that

**Comment by tonyleelyy** [comment]
> How can I change the lang into english? it is in Chinese or something like that

I can't understand... Both guides are in English.

**Comment by tonyleelyy** [comment]
> it required from me acess to the internet and I dont see any wifi driver inside..

Wi-Fi driver is included in my [EFI](https://github.com/tonyleelyy/OpenCore-Hackintosh-Dell-G3-3579/releases/tag/v4.3).

**Comment by TheMarteh** [comment]
> How can I change the lang into english? it is in Chinese or something like that

In your config.plist, remove the entry at prev-lang:kbd on first boot. Make the data be just <>. The code that's in there changes the language on startup to chinese. If you install without changing this value everything will be in chinese.

**Comment by Ravid-Levy** [comment]
it doesn't work the wifi driver..

Can you give me dmg file that will be compatible with 10.15 MacOS and g3 3579?

I can see just the ethernet.

**Comment by Ravid-Levy** [comment]
> > How can I change the lang into english? it is in Chinese or something like that
> 
> In your config.plist, remove the entry at prev-lang:kbd on first boot. Make the data be just <>. The code that's in there changes the language on startup to chinese. If you install without changing this value everything will be in chinese.

if you can or the author can it will be fine.

**Comment by tonyleelyy** [comment]
> it doesn't work the wifi driver..
> 
> Can you give me dmg file that will be compatible with 10.15 MacOS and g3 3579?
> 
> I can see just the ethernet.

That is beyond my ability. Sorry.

**Comment by Ravid-Levy** [comment]
I fixed all by myself.
thank you for no help.

**Comment by tonyleelyy** [comment]
Thank you for wasting our time.
