### ISSUE TITLE
BIOS配置

### ISSUE THREAD

**Issue by hackerschen** [tonyleelyy/OpenCore-Hackintosh-Dell-G3-3579#4]
黑果小兵里面的bios里面要关闭和开启的东西，我再dell的bios里面一个也找不到，那么要进行配置吗

**Comment by tonyleelyy** [comment]
不至于一个也找不到吧，你先更新BIOS再仔细找找，很多都是名称的首字母缩写，至少我是能找到几个的。

有些实在没有的，就不用管了，可以直接安装。

**Comment by hackerschen** [comment]
直接安装是这个样子
![IMG_20200416_145851](https://user-images.githubusercontent.com/48798399/79441934-7178ec80-800a-11ea-8b13-0549c0dd057c.jpg)

**Comment by hackerschen** [comment]
不知道该怎么办了

**Comment by tonyleelyy** [comment]
> 直接安装是这个样子
> ![IMG_20200416_145851](https://user-images.githubusercontent.com/48798399/79441934-7178ec80-800a-11ea-8b13-0549c0dd057c.jpg)

你这是进了Windows吧？你改了config.plist里的showpicker没？

**Comment by hackerschen** [comment]
我的具体做法是，下载一个官网的oc，然后用的oc来替换efi的oc文件夹，镜像是写入了，然后替换u盘里面的efi，启动就这样了，他们好像都没改boot，所以我使用的是原来的boot 9.4kb的那个，这样安装对吗，你开始说每个人的boot都应该不一样，但是我看教程的时候一般他们都是直接下载官网的，然后修改oc里面的内容boot没有改动，这我很困惑

**Comment by hackerschen** [comment]
没改

**Comment by hackerschen** [comment]
![image](https://user-images.githubusercontent.com/48798399/79442579-50fd6200-800b-11ea-8890-75f538280c60.png)
功能这样吗那个选项

**Comment by tonyleelyy** [comment]
出现你上面这个蓝屏，就代表系统找不到引导分区，但是这只会出现在Windows系统下。
如果你开机选择OC进入，还是出现上面这个画面的话，意味着或许你用OC启动了Windows系统，而不是macOS的安装程序。
ShowPicker这个功能就是让你能进入OC之后能选择macOS的安装盘。

**Comment by tonyleelyy** [comment]
另外在安装阶段你不用改电脑本身的EFI分区，直接改U盘里的那个。

将U盘里的 /OC 删除，将我的那个复制进去，改 ShowPicker 为True

安装好之后可以在Windows将我提供的OC复制到电脑本身的EFI分区

**Comment by tonyleelyy** [comment]
请问成功了吗？

我这里有改好ShowPicker的config.plist，直接替换即可，请成功后再告诉我一下。

[config.zip](https://github.com/tonyleelyy/OpenCore-Hackintosh-Dell-G3-3579/files/4487889/config.zip)

**Comment by hackerschen** [comment]
改好了，谢了

**Comment by hackerschen** [comment]
但是，好像不能引导windows，还有为什么你的boot文件大小大一点，做了什么优化吗，还是添加了windos的支持引导

**Comment by hackerschen** [comment]
那个ShowPicker的选项，安装完成后要改为false吗

**Comment by hackerschen** [comment]
上面说长期使用改为false，有什么好处吗

**Comment by tonyleelyy** [comment]
这个OC因为涉及改名（我们的笔记本必须这么做），所以不会支持Windows的，你直接开机选那个UEFI启动Windows就行了。如果还是不行的话，你要自行百度一下怎么在PE里面修复Windows引导了。

我的Boot就是机器一开始的文件，没做任何改动。

ShowPicker就是显示一个选择系统的菜单而已，没有任何好处。如果你不需要，想F12选OC直接打开macOS的话，可以将它改成false，然后下面还有一个选项timeout改成0。

其实也有一个好处，就是开机会快一点哈哈哈，毕竟不用手动选择系统嘛。

感谢你的反馈。

**Comment by hackerschen** [comment]
我觉得，应该是我谢谢你的解答才对

**Comment by tonyleelyy** [comment]
哈哈，今天两个朋友提出issue，我还以为我上传的文件出问题了。

我之后会在这个项目里添加更多说明，你们的反馈会帮助更多使用这个项目的人。咱们一起进步！
