### ISSUE TITLE
Intel Wireless-AC 9462 is not working

### ISSUE THREAD

**Issue by JYBWOB** [tonyleelyy/OpenCore-Hackintosh-Dell-G3-3579#40]
Intel Wireless-AC 9462 is the original computer network card. I haven't changed this device.

What is working (the first) is an external usb wireless network card.
![image](https://user-images.githubusercontent.com/44292122/99901374-3d2c8380-2cf1-11eb-86d4-07b8c43980c8.png)

**Comment by mehmetyukcell** [comment]
https://github.com/OpenIntelWireless

**Comment by JYBWOB** [comment]
> https://github.com/OpenIntelWireless

Thank u! It works
