### ISSUE TITLE
About DSDT 

### ISSUE THREAD

**Issue by StevenKim523** [tonyleelyy/OpenCore-Hackintosh-Dell-G3-3579#42]
Sorry to bother you again. My laptop isn't G3 but MSI GF63 8RC. These two laptop have nearly same hardware. For now, it works perfectly on my laptop. Could I reduce the amount of DSDT or If I need to get my laptop's DSDT and add them to config.plist?
Thanks!

**Comment by jinpan523** [comment]
> Sorry to bother you again. My laptop isn't G3 but MSI GF63 8RC. These two laptop have nearly same hardware. For now, it works perfectly on my laptop. Could I reduce the amount of DSDT or If I need to get my laptop's DSDT and add them to config.plist? Thanks!

**Comment by tonyleelyy** [comment]
If this EFI's DSDT works perfectly on your laptop, there's no need to change it.
But some parts of the hardware may be in different positions, and it would be perfect if you could make a new one yourself.
