### ISSUE TITLE
Merge 'hi-dpi patch' ?

### ISSUE THREAD

**Issue by DongRih** [tonyleelyy/OpenCore-Hackintosh-Dell-G3-3579#43]
The patch is as seen on https://github.com/xzhih/one-key-hidpi

G3-3579 has an 15.6" 1080p screen, on which the default font and ui seems unpleasantly small, but choosing lower resolution in system settings makes everything fuzzy. Merging this patch may help with the problem.

**Comment by StevenKim523** [comment]
Does one-key-hidpi have some bugs? Such as the Apple logo becomes bigger or wake from hibernating then the display gets wrong in resolution.

**Comment by tonyleelyy** [comment]
That hi-dpi patch works by changing files in system volumes. Can't be merged in the EFI.
Run that script manually if you need it.
