### ISSUE TITLE
Can't wake from hibernate

### ISSUE THREAD

**Issue by DongRih** [tonyleelyy/OpenCore-Hackintosh-Dell-G3-3579#44]
After trying to wakeup by pressing power button, the screen was still black. But peripheral devices seemed to get power, as the light of my usb mouse turned on.

Apple diagnosis file is attached below.

[Sleep Wake Failure_2020-11-30-g3-3579.txt](https://github.com/tonyleelyy/OpenCore-Hackintosh-Dell-G3-3579/files/5614745/Sleep.Wake.Failure_2020-11-30-g3-3579.txt)

**Comment by tonyleelyy** [comment]
I found that same issue in Apple Community. That might be a bug in macOS.
https://discussions.apple.com/thread/251768285

I will look into that in these days.

**Comment by DongRih** [comment]
> I found that same issue in Apple Community. That might be a bug in macOS.
> https://discussions.apple.com/thread/251768285
> 
> I will look into that in these days.

Thank you.

**Comment by DongRih** [comment]
applicable workaround
> disable power nap from 
> 
> >System Preferences>Energy Saver

@tonyleelyy  I guess adding this to README file may be helpful.

**Comment by tonyleelyy** [comment]
> applicable workaround
> 
> > disable power nap from
> > >System Preferences>Energy Saver
> 
> @tonyleelyy I guess adding this to README file may be helpful.

Thank you very much! I will add it alongside your name after I try it out.

**Comment by tonyleelyy** [comment]
I'm so sorry that I went on a holiday leaving my laptop at school. 
But I will update README as soon as I come back.
Thanks again for your contribution!
