### ISSUE TITLE
DHCP won't get ip automatically when switching wireless network

### ISSUE THREAD

**Issue by DongRih** [tonyleelyy/OpenCore-Hackintosh-Dell-G3-3579#45]
**wireless adapter: Intel Wireless-AC 9462 (comes with G3-3579)
driver: itlwm: 1.1.0 (comes with release v4.3 of this repository)**

problem: when switching from one wifi network to another, DHCP won't get ip automatically for a long period of time, thus the network won't work (though network was connected successfully). I have to renew DHCP manually to make the newly connected network function properly.

<img width="651" alt="图片" src="https://user-images.githubusercontent.com/35327409/101241618-a5885580-3732-11eb-8e0d-24eb812f0002.png">

**Comment by tonyleelyy** [comment]
这个可能得找itlwm的作者了，驱动还得等大佬慢慢完善啊~

暂时不知道怎么解决了，真要完美可以买博通的卡。
