### ISSUE TITLE
macOS Big Sur 11.1更新后问题

### ISSUE THREAD

**Issue by JYBWOB** [tonyleelyy/OpenCore-Hackintosh-Dell-G3-3579#46]
更新到Big Sur 11.1时
更新过程以及更新后开机 都会长时间(几分钟)卡在苹果logo界面
(长时间等待后仍可进入系统正常使用，但影响体验)

**Comment by tonyleelyy** [comment]
或许需要更新到OC 0.6.4来解决问题，不过0.6.4更新可能需要[另外的步骤](https://github.com/acidanthera/bugtracker/issues/1222#issuecomment-739241310)，目前还在观望中。
感谢你的反馈！

**Comment by JYBWOB** [comment]
> 或许需要更新到OC 0.6.4来解决问题，不过0.6.4更新可能需要[另外的步骤](https://github.com/acidanthera/bugtracker/issues/1222#issuecomment-739241310)，目前还在观望中。
> 感谢你的反馈！

经测试，当由11.0升级到11.1时会出现开机卡的情况。直接安装系统11.1后不会出现这个情况。
这个问题要不要Close你来决定~

**Comment by tonyleelyy** [comment]
十分感谢你的测试！我暂时先Close了，EFI确实还有些不太完善，等我考完试会再研究一下。非常感谢！:smile:
