### ISSUE TITLE
can I make dual boot with existing Windows10 came with DELL G3 3579. 

### ISSUE THREAD

**Issue by vmadhavan15** [tonyleelyy/OpenCore-Hackintosh-Dell-G3-3579#47]
can I make dual boot with existing Windows10 came with DELL G3 3579.  I have 512 GB SSD harddrive wanted to make dual boot along with Windows10 and Mac 11

is there any video tutorial for making it success

**Comment by tonyleelyy** [comment]
Of course you can.

Just put my /OC folder into the original EFI partition of your Windows 10.
Create new partition in your SSD in Windows.
Install your macOS into that partition.

Video tutorial: 
https://www.youtube.com/watch?v=mwcsKGvS6uo
https://www.youtube.com/watch?v=fdQivDt10NM

**Comment by vmadhavan15** [comment]
Hi Tony 

I have downloaded the OLARILA catalina raw file and used balenaetcher to write to USB drive. after writing to USB i tried to boot from USB drive but it did not boot.

Also I placed the /OC folder into my Windows EFI partition too. but nothing worked out..

I have tried to use Catalina which I download from Niresh Catalina version and I replaced the OC into EFI partition of the USB disk 

is it fine to use that Niresh Catalina version or else which one to use

Please share the Mac OS DMG link
