### ISSUE TITLE
G3 如何外接显示器

### ISSUE THREAD

**Issue by prozyy** [tonyleelyy/OpenCore-Hackintosh-Dell-G3-3579#48]
你好，我的是G3 带type-C版本，网上找了很多EFI都不能使用type-C 转hdmi外接显示器，大佬能否给出个适配Type-C的版本(支持外接显示器)

**Comment by tonyleelyy** [comment]
抱歉，我那台电脑不带type-c，没有设备太难适配了，建议另寻他路吧...
十分抱歉
