### ISSUE TITLE
Tried installing Catalina on G3 3579

### ISSUE THREAD

**Issue by vmadhavan15** [tonyleelyy/OpenCore-Hackintosh-Dell-G3-3579#49]
Hi Tony

I have downloaded the OLARILA catalina raw file and used balenaetcher to write to USB drive. after writing to USB i tried to boot from USB drive but it did not boot.

Also I placed the /OC folder into my Windows EFI partition too. but nothing worked out..

I have tried to use Catalina which I download from Niresh Catalina version and I replaced the OC into EFI partition of the USB disk

is it fine to use that Niresh Catalina version or else which one to use

Please share the Mac OS DMG link

**Comment by Skr-Skr** [comment]
Don't boot from USB drive, but boot it from OC
Add a OC Boot-Item and boot it
if the USB driver is inserted ，u can see a new item in OC

**Comment by JYBWOB** [comment]
> Hi Tony
> 
> I have downloaded the OLARILA catalina raw file and used balenaetcher to write to USB drive. after writing to USB i tried to boot from USB drive but it did not boot.
> 
> Also I placed the /OC folder into my Windows EFI partition too. but nothing worked out..
> 
> I have tried to use Catalina which I download from Niresh Catalina version and I replaced the OC into EFI partition of the USB disk
> 
> is it fine to use that Niresh Catalina version or else which one to use
> 
> Please share the Mac OS DMG link

Don't boot from USB drive, but boot it from OC
Add a OC Boot-Item and boot it
if the USB driver is inserted ，u can see a new item in OC

**Comment by tonyleelyy** [comment]
The comment above is right. Just add the OC in your BIOS, then any macOS drive would be fine.

I only know two Chinese sites that share great install files:
https://blog.daliansky.net/
http://bbs.pcbeta.com/viewthread-1858946-1-1.html

**Comment by vmadhavan15** [comment]
I will try the same and install the Mac OS
