### ISSUE TITLE
请教一下启动oc出错的问题，该怎么解决

### ISSUE THREAD

**Issue by 428255177** [tonyleelyy/OpenCore-Hackintosh-Dell-G3-3579#5]
在gibmacos写入u盘的镜像，加入了佬哥您的oc文件，和imacos下载的oc最新boot，改了ShowPicker，bios中的设置按照黑果小兵上的修改，但是开机还是出错，不知道是哪里的问题了，希望佬哥能帮帮忙解决一下。我的笔记本配置和你的是一样的
![IMG_20200416_205451](https://user-images.githubusercontent.com/63795753/79462764-7bd5bf00-7fe7-11ea-96b6-b0b86fb80be8.jpg)

**Comment by tonyleelyy** [comment]
这个是config.plist丢失或损坏导致的，你的/EFI/OC文件夹截个图我看看？

**Comment by 428255177** [comment]
![IMG_20200416_221722](https://user-images.githubusercontent.com/63795753/79467159-053bc000-7fed-11ea-989d-38b40c2a31a0.jpg)
我是用记事本直接修改的ShowPicker  会不会是这个原因

**Comment by tonyleelyy** [comment]
那肯定是了，修改OC的.plist文件一定要使用[ProperTree](https://github.com/corpnewt/ProperTree)，你先安装一下[Python](https://www.python.org/downloads/)，然后clone那个ProperTree项目，打开.bat就可以修改plist了。

或者，你也可以直接使用我帮你修改好的版本哈哈哈
[config.zip](https://github.com/tonyleelyy/OpenCore-Hackintosh-Dell-G3-3579/files/4487852/config.zip)

搞定了记得回来告诉我一声！

**Comment by tonyleelyy** [comment]
我发现好多朋友都困在了ShowPicker这一步，我找个时间改改我的EFI，默认把这一项打开吧。

**Comment by 428255177** [comment]
终于弄好了，谢谢谢谢。现在就还有一个问题了，按照clover引导界面添加win10启动的方法 在oc上却不行，不知道佬哥可有方法

**Comment by tonyleelyy** [comment]
> 终于弄好了，谢谢谢谢。现在就还有一个问题了，按照clover引导界面添加win10启动的方法 在oc上却不行，不知道佬哥可有方法

我们这个OC因为涉及改名和机型名称的修改，无法支持Windows启动。OC不像Clover那样会自动给Windows绕过config的设置，就不能启动Windows了。

咱们还是直接使用UEFI启动Windows吧哈哈。

**Comment by 428255177** [comment]
佬哥能不能做个Clover  第一次使用oc，感觉还是clover方便一点，但是没有大神做10.15版本

**Comment by tonyleelyy** [comment]
> 佬哥能不能做个Clover 第一次使用oc，感觉还是clover方便一点，但是没有大神做10.15版本

呃这就有点难了。这个OC配置好了我觉得没回到Clover的必要了。

OC虽然是麻烦，但是之后那些大神的驱动更新都是根据OC适配的了。OC显然是更长远的选择。

如果真的想在OC启动Windows的话，或许可以尝试一下这个：http://bbs.pcbeta.com/viewthread-1838814-1-1.html

其实我觉得OC去掉ShowPicker直接默认启动macOS也不怎么麻烦吧。开机按F12就可以选择系统了。
