### ISSUE TITLE
Work on device with only 1TB HDD?

### ISSUE THREAD

**Issue by Qiangong2** [tonyleelyy/OpenCore-Hackintosh-Dell-G3-3579#50]
My model of the 3579 does not have the 512GB SSD, only the 1TB HDD. Will it still work as a hackintosh? Or should I stick to Ubuntu Kylin for the time being?

**Comment by tonyleelyy** [comment]
Of course it works.

**Comment by vmadhavan15** [comment]
Hi Tony, I have followed all the steps and installed catalina on my laptop but my catalina got updated with Big Sur and WIFI is not working now.. any solution.. please help me

**Comment by tonyleelyy** [comment]
> Hi Tony, I have followed all the steps and installed catalina on my laptop but my catalina got updated with Big Sur and WIFI is not working now.. any solution.. please help me

I have uploaded Big Sur EFI in the release page, replace your EFI with that.

**Comment by vmadhavan15** [comment]
> > Hi Tony, I have followed all the steps and installed catalina on my laptop but my catalina got updated with Big Sur and WIFI is not working now.. any solution.. please help me
> 
> I have uploaded Big Sur EFI in the release page, replace your EFI with that.

once updated I have to replace the BIG SUR EFI on my EFI partition isnt it? let me try the same thank you Tony

**Comment by tonyleelyy** [comment]
> > > Hi Tony, I have followed all the steps and installed catalina on my laptop but my catalina got updated with Big Sur and WIFI is not working now.. any solution.. please help me
> > 
> > 
> > I have uploaded Big Sur EFI in the release page, replace your EFI with that.
> 
> once updated I have to replace the BIG SUR EFI on my EFI partition isnt it? let me try the same thank you Tony

You're welcome :D
