### ISSUE TITLE
Installer stuck at 1 minute left

### ISSUE THREAD

**Issue by Qiangong2** [tonyleelyy/OpenCore-Hackintosh-Dell-G3-3579#52]
![20210213_130836](https://user-images.githubusercontent.com/16091790/107861749-a279a780-6dfc-11eb-96aa-e510fc92d7ce.jpg)

The installer is just stuck at 1 minute left. Any help is appreciated

**Comment by mehmetyukcell** [comment]
> ![20210213_130836](https://user-images.githubusercontent.com/16091790/107861749-a279a780-6dfc-11eb-96aa-e510fc92d7ce.jpg)
> 
> 
> 
> The installer is just stuck at 1 minute left. Any help is appreciated

What is your ssd?

**Comment by Qiangong2** [comment]
After an hour and a half it rebooted on its own. It is working now. I have a 1TB HDD
Closing
