### ISSUE TITLE
Drop in wireless connectivity after sleep

### ISSUE THREAD

**Issue by Qiangong2** [tonyleelyy/OpenCore-Hackintosh-Dell-G3-3579#53]
I've set up Big Sur and it's working great so far. However, whenever my laptop goes to sleep/hibernates, the wireless connectivity drops and barely connects at all. Even when it does connect, it will only stay connected for about 5-10 minutes before disconnecting.

It works perfectly fine and I get full speed right after bootup though

**Comment by tonyleelyy** [comment]
应该是无线驱动的问题，尝试替换最新版的驱动：
https://github.com/OpenIntelWireless/itlwm
https://github.com/OpenIntelWireless/IntelBluetoothFirmware
