### ISSUE TITLE
大佬，有线网插上没反应是啥情况？

### ISSUE THREAD

**Issue by huisheng123666** [tonyleelyy/OpenCore-Hackintosh-Dell-G3-3579#54]

**Comment by tonyleelyy** [comment]
1. 先排除系统以外的问题，关掉VPN，将电脑插到另一个 网口/网线 上看看，也重启路由器看看。
2. 重置 macOS 的网络设置：https://zihengcat.github.io/2017/07/30/macintosh-macos-reset-network/
