### ISSUE TITLE
Alt key & Start key just swap

### ISSUE THREAD

**Issue by georgengx** [tonyleelyy/OpenCore-Hackintosh-Dell-G3-3579#55]
After the update 6 days ago, my hackintosh just swap Alt key & Start key

**Comment by tonyleelyy** [comment]
That's because the positions of the Alt and Start keys are reversed by default in Macs, compared with Windows Keyboards.
You can change those key's function in System Preferences: https://9to5mac.com/2016/03/17/how-to-remap-windows-keyboard-buttons-match-mac-layout/
