### ISSUE TITLE
AirportItlwm does not load

### ISSUE THREAD

**Issue by henriqueof** [tonyleelyy/OpenCore-Hackintosh-Dell-G3-3579#56]
Hello, I am trying to install macOS Big Sur along my current Windows 10 installation and performed the following steps:

- Generate installation media using macOS
- Download you EFI from master branch (the readme says it supports 11.2.2)
- Copied OC and replaced Boot folders on Windows EFI partition
- Created a partition on SSD, booted installer and installed on said partition
- After installer finish a new option appear to finish installation
- When select installation boot option it shows the apple logo for ~2 secs and reboots
- It keeps rebooting until I forcelly reboot and can get back to OC menu and select Windows

Any clue on why this happens? My notebook is exactly the one this repo is expecting.

Thanks for any help.

**Comment by tonyleelyy** [comment]
Have you tried the version I updated on March 2？
I'm sorry that the latest release of this repo is outdated and might be not usable on 11.2.2.

**Comment by tonyleelyy** [comment]
Other solutions:
- reset NVRAM on OC
- add "-v" to "boot-args" on config.plist, reboot, and take a picture/video of the error log, then post it here. I can help if you don't know how to do that :)

**Comment by henriqueof** [comment]
Hello, thanks for quickly reply.

Yes, the last commit was on March 2nd, it is the one I am using.
Tried NVRAM reset already.
I added the -v option but it reboots almost instantaneously so I can't read. (maybe there is a way to disable auto reboot?).

Will try the latest release with 11.0.1 tomorrow (maybe more stable?)

If you can share any recommendation on what is the best way/most stable installation process I'd be very grateful.

**Comment by tonyleelyy** [comment]
> Hello, thanks for quickly reply.
> 
> 
> 
> Yes, the last commit was on March 2nd, it is the one I am using.
> 
> Tried NVRAM reset already.
> 
> I added the -v option but it reboots almost instantaneously so I can't read. (maybe there is a way to disable auto reboot?).
> 
> 
> 
> Will try the latest release with 11.0.1 tomorrow (maybe more stable?)
> 
> 
> 
> If you can share any recommendation on what is the best way/most stable installation process I'd be very grateful.

Maybe capture it with slow motion? That's the method I always use.

The log is the key information to solve your problem. It would be helpful if you can get it.

**Comment by henriqueof** [comment]
I used slow motion and managed to capture some log, after a quick search turns out that I needed to disable SecureBootModel.

Now I can get past the initial two seconds of installation but other problem arised, after some seconds I see a lot of "device is write locked" and the computer restarts.

Trying to capture logs and find out the reason.

**Comment by henriqueof** [comment]
After disabling SecureBootModel I deleted the installer partition and created it again, now I managed to finish the installation!

System seems stable but froze twice when I was using it, WiFi did not worked, it shows WiFi log but can't find any network, I used USB tethering on my phone to access internet.

Thank you very much for your work!

**Comment by tonyleelyy** [comment]
Congrats!
Did you still installed macOS Big Sur?
If not，then you might need to change an kext to make WiFi work:
https://github.com/OpenIntelWireless/itlwm/releases/tag/v1.2.0

Try these steps if you are using Big Sur:
- Do not reboot from Windows, turn off your computer and boot to macOS from OC directly.
- Download AirportItlwm from the link above and replace the old one in your EFI.
- Reset nvram
- Try to build your own USBPorts.kept

Hope these can help you.：）

**Comment by henriqueof** [comment]
Hello again,

Yes, I installed Big Sur 11.2.2.

Everything seems to be working fine except for WiFi.

I tried updated the AirportItlwm kext but it won't load on boot.

Tried resetting NVRAM too,

On AirportItlwm docs, it says that secure boot must be enabled, even though I enabled it after install I installed the system with it disabled, maybe that's the problem?

I tried loading it via terminal but it won't work either, says the the kext failed to load.

Does the USBPorts has something to do with the WiFi driver? I didn't tried it yet because I couldn't find a good documentation on it.

**Comment by tonyleelyy** [comment]
Hello, sorry for the late reply.
Secure Boot might not be the problem since you have already enabled it.

I'm not sure if the USBPorts.kext didn't work properly in your computer. 
But if we want to use WiFi, we need to enabled a specific port for it in USBPorts.kext，which I have already configured for G3 3579 and haven't received any issue about it yet.

For the time being, I have no idea about other solutions🤔.

**Comment by tonyleelyy** [comment]
Still don't know how to solve your problem, sorry.
I'll close this issue for now.

**Comment by henriqueof** [comment]
No problem, thanks for your help.
I will continue to experiment with this Hackintosh and if I find it valuable for my productivity I may invest in one of those Fenvi adapters, do you have any opinion on them?

**Comment by tonyleelyy** [comment]
Fenvi adapters applies to those who have PCI-E slots. What you need for G3 is the Broadcom cards inside.
You can just buy a BCM94360Z4 / DW1820A / BCM94350ZAE / BCM94356ZEPA50DX to replace your intel card.
Those cards are pretty expensive in China right now, so I haven't tried them yet :(
