### ISSUE TITLE
Trouble with Facetime 

### ISSUE THREAD

**Issue by georgengx** [tonyleelyy/OpenCore-Hackintosh-Dell-G3-3579#57]
Still make the call but i cant hear anything,
 audio still work

**Comment by tonyleelyy** [comment]
Hi, benhsmif.
Please check your video output setting in FaceTime:
![image](https://user-images.githubusercontent.com/61397664/114261804-45baf780-9a0f-11eb-92ae-61099e0c6b90.jpeg)
