### ISSUE TITLE
Slow boot and work OS

### ISSUE THREAD

**Issue by Stelette** [tonyleelyy/OpenCore-Hackintosh-Dell-G3-3579#59]
Hello, please help me, I use your EFi for my Hackintosh Big Sur. But my loading is very slow,about 2 minutes, and in the process of the system itself, it slows down a lot, although with my characteristics this should not be. My laptop is similar to yours.Specifications:
Processor-Intel Core i7-8750H
VIDEO-Intel (R) UHD Graphics 630 + GeForce GTX 1060 with Max-Q design (6 GB)
Wi-Fi-Intel (R) Wireless-AC 9462
SOUND - Realtek ALC236
Laptop Model: Dell G3 3779
I tried to build an assembly based on the guide from OpenCore,but there was an error in the process, there was a panic, the solution options did not help,but if I put quirck as in your config.plist,it worked,but it also slows down.Can you tell me why this situation may be?

**Comment by Stelette** [comment]
The problem was solved quite simply, I moved the system to an external hard drive and everything was fine=) (before that, a partition was allocated on the laptop's hard drive, which is used as my data storage)

**Comment by tonyleelyy** [comment]
Thank you for your reporting ：）

**Comment by Stelette** [comment]
The problem turned out to be in the system, I had Big Sur, and now I put Catalina (I made an update to Big Sur and friezes appeared again)in the end, I roll back to Catalina
