### ISSUE TITLE
10.14可用

### ISSUE THREAD

**Issue by sky2000fo** [tonyleelyy/OpenCore-Hackintosh-Dell-G3-3579#6]
10.14更换此oc后正常引导，准备升级最新版，安装网卡 蓝牙驱动。很给力！

**Comment by tonyleelyy** [comment]
感谢支持！也感谢你的评论，我本来也不知道旧版本能否正常使用，你这么一说我就安心了嘿嘿！

**Comment by sky2000fo** [comment]
以前找过oc 结果用不了，今天一看发现你的还增加了int的WiFi，下载一试！直接启动，非常感谢作者！

---原始邮件---
发件人: "tonyleelyy"<notifications@github.com&gt;
发送时间: 2020年4月21日(周二) 晚上10:26
收件人: "tonyleelyy/OpenCore-Hackintosh-Dell-G3-3579"<OpenCore-Hackintosh-Dell-G3-3579@noreply.github.com&gt;;
抄送: "sky2000fo"<1753319929@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [tonyleelyy/OpenCore-Hackintosh-Dell-G3-3579] 10.14可用 (#6)




 
感谢支持！也感谢你的评论，我本来也不知道旧版本能否正常使用，你这么一说我就安心了嘿嘿！

**Comment by tonyleelyy** [comment]
WiFi目前还不太完善，要看驱动的作者何时完成更新了。

如果使用有问题的话欢迎提出！我们一起进步！

**Comment by sky2000fo** [comment]
网卡已经驱动，但是每次重启都要输入命令



---原始邮件---
发件人: "tonyleelyy"<notifications@github.com&gt;
发送时间: 2020年4月22日(周三) 凌晨0:26
收件人: "tonyleelyy/OpenCore-Hackintosh-Dell-G3-3579"<OpenCore-Hackintosh-Dell-G3-3579@noreply.github.com&gt;;
抄送: "sky2000fo"<1753319929@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [tonyleelyy/OpenCore-Hackintosh-Dell-G3-3579] 10.14可用 (#6)




 
Closed #6.

**Comment by tonyleelyy** [comment]
> 网卡已经驱动，但是每次重启都要输入命令
> […](#)
> ---原始邮件--- 发件人: "tonyleelyy"<notifications@github.com&gt; 发送时间: 2020年4月22日(周三) 凌晨0:26 收件人: "tonyleelyy/OpenCore-Hackintosh-Dell-G3-3579"<OpenCore-Hackintosh-Dell-G3-3579@noreply.github.com&gt;; 抄送: "sky2000fo"<1753319929@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题: Re: [tonyleelyy/OpenCore-Hackintosh-Dell-G3-3579] 10.14可用 (#6) Closed #6. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

是的，目前此驱动还不支持放入OC目录，而且网速会很慢，请耐心等待作者的更新。

**Comment by sky2000fo** [comment]
好的 谢谢！



---原始邮件---
发件人: "tonyleelyy"<notifications@github.com&gt;
发送时间: 2020年4月22日(周三) 下午4:03
收件人: "tonyleelyy/OpenCore-Hackintosh-Dell-G3-3579"<OpenCore-Hackintosh-Dell-G3-3579@noreply.github.com&gt;;
抄送: "sky2000fo"<1753319929@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [tonyleelyy/OpenCore-Hackintosh-Dell-G3-3579] 10.14可用 (#6)




  
网卡已经驱动，但是每次重启都要输入命令
 …
 ---原始邮件--- 发件人: "tonyleelyy"<notifications@github.com&gt; 发送时间: 2020年4月22日(周三) 凌晨0:26 收件人: "tonyleelyy/OpenCore-Hackintosh-Dell-G3-3579"<OpenCore-Hackintosh-Dell-G3-3579@noreply.github.com&gt;; 抄送: "sky2000fo"<1753319929@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题: Re: [tonyleelyy/OpenCore-Hackintosh-Dell-G3-3579] 10.14可用 (#6) Closed #6. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
是的，目前此驱动还不支持放入OC目录，而且网速会很慢，请耐心等待作者的更新。
