### ISSUE TITLE
Trackpad and bluetooth mouse (Logitech m590)

### ISSUE THREAD

**Issue by diablos872001** [tonyleelyy/OpenCore-Hackintosh-Dell-G3-3579#60]
Dear tonyleelyy,
I'm an italian guy who have the exaclty G3 3579 as yours (8300H + GTX 1050)
In the past I made a Dell Mini9 with OSX, but long time ago. All working, cheap hackintosh.

So I am writing you before starting this idea/work on the G3.

I have a 250gb M2 with windows, that I want to leave in this way.
I Updated my G3 with a SSD 500gb on the free slot Sata3, and I want to install OSX here.
Do you think is it a good idea? To leave untouched the primary HD (M2) and work on the secondary SSD.

Other thing: I don't have a real Mac.
Years ago I use the application "transmac" that can create a bootable usb with a MAC dmg image.
So I dowloaded an image of macOS Big Sur 11.2.2 (20D80).

If I correctly read on other post that you wrote, I must proceed in with way:
1 - Make an macOS installation USB drive (WITH TRANSMAC AS I WOTE ABOVE)
2 - Put my EFI (download in my release page)into the EFI partition on your USB drive.
3 - Add EFI/Boot/BOOTx64.efi to your boot sequence in BIOS
4 - Boot and install macOS

Correct?
Thanks for your answer and kindness.
Marco

**Comment by tonyleelyy** [comment]
It is a good idea to install macOS in that 500Gb SSD. You can still use your M.2 SSD in your system.
The methods are totally correct, and you can use TransMac as before.
Enjoy your macOS~

**Comment by diablos872001** [comment]
Dear, first problem.
I create a 200mb EFI partition and then copied your two folder in it.
Changed the bios configuration to added the bootx64.efi to boot sequence.
I got stuck in OpenCore, the installation partition is not showing.
When I use transmac, I need to do other than restore the 11.2.2 on it? like copy something (files) or similar?

**Comment by diablos872001** [comment]
Dear, I successfully installed BigSur 11.3.1 from USB!
With transmac a lot of trouble, then I've prepared an USB with Rufus (all FAT32) and then all gone.

Now I may ask you a thing about trackpad and mouse:
- My trackpad doesn't recognize the two buttons, for left click and right click, is it normal?
- I cannot connect with my Logitech m590 Bluetooth mouse, in the panel of bluetooth I see it but when I try to connect it doesn't work.
Thanks for your help.
Marco

**Comment by tonyleelyy** [comment]
You might need to check your trackpad settings in System Preferences,
if it still doesn't work, try this new EFI: https://github.com/CalvinXu17/OpenCore-Dell-G3-3579-1060mq

**Comment by diablos872001** [comment]
The trackpad now works good with custom setting in System preferences, thanks.
For the mouse (Logitech m590) I solved using the usb receiver and not the bluetooth connection.

Now I succesfully update to BigSur 11.4, working well I think.
![Schermata 2021-06-12 alle 09 42 46](https://user-images.githubusercontent.com/84093994/121769228-afb46200-cb62-11eb-88c6-26902f6076eb.png)
