### ISSUE TITLE
3579 1060mq版支持雷电3接口

### ISSUE THREAD

**Issue by CalvinXu17** [tonyleelyy/OpenCore-Hackintosh-Dell-G3-3579#61]
修改机型为MacbookPro16,2或更新机型，并更新USB驱动，添加IOElectrify.kext可在BigSur驱动雷电3，外接显示器或者拓展坞

**Comment by CalvinXu17** [comment]
https://github.com/CalvinXu17/OpenCore-Dell-G3-3579-1060mq

**Comment by tonyleelyy** [comment]
太好了！感谢您的贡献
我稍后在README添加您项目的链接供需要雷电口的朋友使用，可以吗？

**Comment by CalvinXu17** [comment]
> 太好了！感谢您的贡献
> 我稍后在README添加您项目的链接供需要雷电口的朋友使用，可以吗？

好的，没问题
