### ISSUE TITLE
三码问题

### ISSUE THREAD

**Issue by isoulgh** [tonyleelyy/OpenCore-Hackintosh-Dell-G3-3579#62]
首先感谢您的引导文件，请问您知道该怎样获得一个属于自己的三码嘛，我使用您引导里的三码没有问题，但是我去自己生成，只要更改了mlb和rom任意一个值，就无法登录imessage和facetime，相反，序列号和systemuuid我可以任意修改，不会出现无法登录iMessage和facetime的问题

**Comment by tonyleelyy** [comment]
换了码可能需要重新登录id，毕竟相当于你注册一台新的电脑。
