### ISSUE TITLE
Upgrade to macOS 11.3+

### ISSUE THREAD

**Issue by Stelette** [tonyleelyy/OpenCore-Hackintosh-Dell-G3-3579#66]
Hello,tell me, can I expect an update to macOS 11.3+ in the near future ? Since some programs require at least this version.

**Comment by TheVaroX** [comment]
Hi there. I have tested this setup on my personal computer, upgrading from Catalina to Big Sur 11.6, and so far I have had no problems. Greetings from Chile.
![Captura de Pantalla 2021-09-20 a la(s) 23 14 36](https://user-images.githubusercontent.com/15294486/134101671-cb727338-24d4-4e27-b876-728d73297d4c.png)
