### ISSUE TITLE
双硬盘引导

### ISSUE THREAD

**Issue by lanfengxuan** [tonyleelyy/OpenCore-Hackintosh-Dell-G3-3579#7]
我保留了原有的windows 10在ssd中，我把OC拷到SSD的ESP中，设置OC引导，bios一直无法识别引导，提示无boot。我用机械硬盘装的Mac. 设置机械硬盘的OC引导又无法识别SSD中的windows. 请问有什么办法能解决吗。

**Comment by tonyleelyy** [comment]
如果是启动项中没有OC，你可以试试在bios中手动添加/OC/OpenCore.efi作为新的引导项。

如果是OC启动了却没办法启动macOS，尝试使用我的 EFI_Install.zip（改了ShowPicker），看看能否在OC中识别到你机械硬盘里的macOS系统。

另外我的OC引导因为涉及改名等操作，所以是不支持Windows引导的，你可以开机按F12选择Windows启动。

**Comment by tonyleelyy** [comment]
> 我保留了原有的windows 10在ssd中，我把OC拷到SSD的ESP中，设置OC引导，bios一直无法识别引导，提示无boot。我用机械硬盘装的Mac. 设置机械硬盘的OC引导又无法识别SSD中的windows. 请问有什么办法能解决吗。

请问解决了吗？

**Comment by lanfengxuan** [comment]
我没有解决，我增加了了一个Refind做引导

**Comment by tonyleelyy** [comment]
> 我没有解决，我增加了了一个Refind做引导

请问能否提供更详细的报错情况？比如报错的代码，您使用的EFI版本等，以便我完善这个项目。

万分感谢！
