### ISSUE TITLE
风扇问题

### ISSUE THREAD

**Issue by hackerschen** [tonyleelyy/OpenCore-Hackintosh-Dell-G3-3579#9]
使用你最新release的oc安装完成之后，开机风扇一直转是什么问题呢，网上说时cpu一直不能变频，使用你27号修改的能解决这个问题吗

**Comment by tonyleelyy** [comment]
可以尝试一下27号的更新，我也不确定，最近正在验证当中。

不过我使用以前的版本风扇也不怎么转，用iStatus看频率也是正常的，前几天不知道为啥检测不出来变频的档数才重新生成了一下。

你开机之后过久一点再看看风扇转不转，也有可能是开机CPU负载高，或者风扇灰尘多导致的而已，检测过后麻烦告知一下，谢谢了~

**Comment by tonyleelyy** [comment]
我目前检测到是，开机CPU会飙到3.5G左右，风扇运转稍快。但是过10秒左右，开机自启的程序启动完了就降到1点多G了，风扇的声音也随之变小，之后正常使用风扇几乎无声。

我的电脑不久之前拆机清过灰，可能情况会好点。

不知道你的情况是怎么样的。

**Comment by hackerschen** [comment]
我等了五分钟风扇的声音确实变小，但是之后只打开了一个chrome等待10分钟左右，风扇仍然有声音，但是正常使用windows，等几分钟风扇声音会无声

**Comment by hackerschen** [comment]
还有楼主，你的风扇和散热器是全都能拆下来的吗，我只能拆下cpu风扇的螺丝，其他的螺丝拧不动，是有什么开关吗

**Comment by hackerschen** [comment]
楼主的正常使用无声是很快吗，在20分钟内吗

**Comment by tonyleelyy** [comment]
> 还有楼主，你的风扇和散热器是全都能拆下来的吗，我只能拆下cpu风扇的螺丝，其他的螺丝拧不动，是有什么开关吗

我没有拆风扇那些，我直接用个气吹把灰尘都吹没了。网上有G3的拆解视频，真要拆的话可以看看。

**Comment by tonyleelyy** [comment]
> 楼主的正常使用无声是很快吗，在20分钟内吗

很快，在一两分钟左右就无声了。

期间我同样使用chrome，还看了一会4K视频，风扇也是轻微运转而已，关掉视频一两分钟就又恢复无声了。

一顿操作之后CPU基本在40-50摄氏度左右。

**Comment by tonyleelyy** [comment]
哈哈经过这两天的观察，我发现我的电脑反而在启动 Windows 的时候风扇有时狂转，所以我估计是电脑的散热本来就有些抽风，这个问题无解了。

经过观察 macOS 下 CPU 变频也是正常的，暂时先不用管了。

如果风扇还是狂转，电脑温度比较高的话，尝试清灰等操作吧～

感谢反馈！
